### ISSUE TITLE
anko-common should support android.support.v4.app.Fragment

### ISSUE THREAD

**Issue by peleteiro** [Kotlin/anko#107]
Helpers like runOnUiThread, toast and many others should be supported on android.support.v4.app.Fragment not only android.app.Fragment

**Comment by yanex** [comment]
It is actually supported, see `anko-support-v4` artifact.

**Comment by peleteiro** [comment]
On anko-commons the only components that does not work with ```android.support.v4.app.Fragment``` is Dialogs and toasts. Every other component works.

anko-support-v4 brings every anko component with it. We need a ```anko-commons-support-v4```.
