### ISSUE TITLE
Please update repo to v0.8

### ISSUE THREAD

**Issue by greenspand** [Kotlin/anko#110]
Hi all. I updated the koltin plugin and needed to update anko as well to reflect the changes. However, v0.8 is not yet uploaded.
Please upload it thx allot.
Cheers. And awesome library/language, amaesing.

**Comment by tmiyamon** [comment]
I'm also waiting for the updating which has the compatibility to the kotlin beta2.

**Comment by greenspand** [comment]
Quick tip. You can still use the v0.7 despite the fact the eystem is showing that dreaded notification to update library. Also, if you use kotlin.x.synthetic injections don't forget to clear chached resources in onDestroyView() method. It is still a bug.

**Comment by Ribesg** [comment]
I want to understand why this is still not done.
I see other changes after 0.8, is 0.8 done or not @yanex?
Do we have to wait for a 0.8.1?

Thanks

**Comment by greenspand** [comment]
Please update the repo. I have a production ready small utility app that depends on it.I mean I could rewrite it but I just love the Anko Library it eases my life.

**Comment by yanex** [comment]
Well, 0.8 is not fully ready right now, but I can release the 0.8-rc version.

**Comment by Ribesg** [comment]
Thanks for the info, I'll just stay on Beta 1 for now!

**Comment by vincaslt** [comment]
When is 0.8 being released? Is there any way to use it in my project already?

**Comment by greenspand** [comment]
Hi vincaslt. You can replace the exact version with + , for the latest version. Apparently, the system doesn't complain any longer.

**Comment by vincaslt** [comment]
Yes, but latest version in repository is v0.7.3. And I'd like to use 0.8.

**Comment by greenspand** [comment]
Does it make a difference?

**Comment by vincaslt** [comment]
AnkoComponent doesn't seem to exist in 0.7.3

**Comment by greenspand** [comment]
I see. Well I wish our tickets would be answered. I mean anko has gained
momentum and it would be a potty if they spoiled their reputation.

**Comment by yanex** [comment]
@greenspand Anko 0.8 will be released on Monday (Nov 30).

**Comment by yanex** [comment]
Done!

**Comment by greenspand** [comment]
Awesome. Thx  alot.
