### ISSUE TITLE
Implicit setContentView in onCreate doesn't work in 0.8

### ISSUE THREAD

**Issue by h0tk3y** [Kotlin/anko#114]
The following code worked in 0.7.3 and works no more in 0.8:

    fun ui() = frameLayout { id = FRAGMENT_HOLDER_ID }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        ui()
        fragmentManager.beginTransaction().replace(FRAGMENT_HOLDER_ID, HelloFragment()).commit()
    }

In debugger I see that in `onCreate` after `ui()` call `findViewById(FRAGMENG_HOLDER_ID)` returns null, while in 0.7.3 it returns the `FrameLayout`.

If I change the call to `setContentView(ui())`, it works.

**Comment by yanex** [comment]
Fixed in 9fddf09bad996609b8396b29d0fbc2de319c3a8e.
