### ISSUE TITLE
Add cheap alternative to 'configuration' for checking only SDK version

### ISSUE THREAD

**Issue by yanex** [Kotlin/anko#118]
Something like

```kotlin
inline fun fromSdk(version: Int, f: () -> Unit) {
    if (Build.VERSION.SDK_INT >= version) f()
}

inline fun ifSdk(version: Int, f: () -> Unit) { //whenSdk?
    if (Build.VERSION.SDK_INT == version) f()
}
```

**Comment by devliber** [comment]
Unfortunately with `doFromSdk` I get the "Call requires API level" error in Android Studio. If I use an `if` statement, the error no longer appears:

![image](https://user-images.githubusercontent.com/31992245/34882571-a0c972b4-f7bf-11e7-9e9f-85d904ebe263.png)

**Comment by SanoKriss** [comment]
Same behavior, what I can do with that, except use if (Build ....) ?

**Comment by mochadwi** [comment]
Any updates on this?
