### ISSUE TITLE
Bug in AttributeParser.kt

### ISSUE THREAD

**Issue by DmitriyZaitsev** [Kotlin/anko#122]
In current implementation I see hardcoded prefixes for general xml namespaces such as ```"http://schemas.android.com/apk/res/android"``` and ```"http://schemas.android.com/tools"``` - ```android``` and ```tools``` respectively.
Unfortunately, your parser can't rely on them and expect that somebody hasn't declared android namespace like:
```
xmlns:notandroid="http://schemas.android.com/apk/res/android"
```
In this case your checks like ```name.startsWith("android:")``` or  ```it.key.replace("android:layout_", "")``` won't work for obvious reasons.

**Comment by yanex** [comment]
I see no reason for supporting that cause (almost) *all* layouts use `android:`, not `notandroid: or something like that.
