### ISSUE TITLE
Proposal: more consistent layout params

### ISSUE THREAD

**Issue by lukaspili** [Kotlin/anko#127]
Current DSL is inconsistent regarding how to set layout params.

Anko offers `lparams` method extension which sets the layout params on the view component.
It would be natural to set it inside the view block declaration.

```kotlin
verticalLayout {
   textView {
      lparams { } // correct
   }.lparams { } // also correct, but less natural
}
```

However because of block composition, calling `lparams` inside the declaration block does not work properly in every case.

```kotlin
verticalLayout {
   lparams { } // lparams is LinearLayout.LayoutParams

   frameLayout {
      lparams { } // lparams is FrameLayout.LayoutParams => INCORRECT, it should be LinearLayout.LayoutParams
   }
}
```

This is why you need to apply the lparams outside the view declaration block.

```kotlin
verticalLayout {
   lparams { } // lparams is LinearLayout.LayoutParams

   frameLayout { }.lparams { } // lparams is LinearLayout.LayoutParams => CORRECT
}
```

But this won't work for views that aren't already encapsulated in an anko DSL block.
The `lparams` is an extension method on `_XXXLayout` classes provided by anko, but not directly on Android layout classes (for valid technical reasons).

```
class MyView(context: Context) : FrameLayout(context) {
   fun setupView() {
      linearLayout {
          lparams { } // Wrong, it's LinearLayout.LayoutParams, but should be FrameLayout.LayoutParams
      }.lparams { } // Does not compile, lparams() doesn't exist on FrameLayout class
   }
}
```

For the last example, you would need to set the layout params in the standard android way, not using anko DSL.

Proposal:

Adopt a single `_LayoutParams` class that would have all the properties from all layout params classes. And it would be the responsibility of the developer to use the correct properties depending what is the  parent container. Like in xml editor when the root layout is <merge>, the auto complete shows all layout params attributes from all containers.

Then there would be only one consistent way to set the layout params, that would work in every cases

```kotlin
verticalLayout {
   layoutParams { } // _LayoutParams

   textView {
      layoutParams { }  // _LayoutParams
   }
}
```

Internally, the `_Layout` would have a builder method that returns the correct layout params instance, depending what attributes have been filled.

I implemented such `_Layout` class in my last project with anko, and it seems to work great.

**Comment by EddieRingle** [comment]
I like this approach as well. The DSL generator could scan for classes extending ViewGroup.LayoutParams and aggregate the fields it finds. It's shame to lose proper type safety, but this is a shortcoming of Kotlin, I suppose. To remedy this somewhat, I believe Lint checks could also be added to warn you if you're using layout properties that are useless for a given parent type.

**Comment by yanex** [comment]
1. We lose the type-safety here. And get the runtime exceptions (or suffer because of undefined behaviour).
2. We can't properly extend such a DSL. Or, at least, I don't see a good way to do this.
3. It adds an another level of abstraction, and it *is not cheap*.

**Comment by eygraber** [comment]
What about having something like this:

```
inline fun <reified R: ViewGroup.LayoutParams> ViewGroup.lparams(
      width: Int = android.view.ViewGroup.LayoutParams.WRAP_CONTENT,
      height: Int = android.view.ViewGroup.LayoutParams.WRAP_CONTENT,
      noinline init: R.() -> Unit = defaultInit
  ): ViewGroup {
    val constructor = R::class.java.getConstructor(Int::class.java, Int::class.java)
    val layoutParams = constructor.newInstance(width, height)
    layoutParams.init()
    this@lparams.layoutParams = layoutParams
    return this
  }
```

This way you have to explicitly specify the type of the parent, so it should be pretty easy to find mistakes.
