### ISSUE TITLE
another way for style implement

### ISSUE THREAD

**Issue by BennyWang** [Kotlin/anko#132]
Now apply style in Anko will go through all the children, if I want to apply more than one style, It will loop several time, I know I can combine style to one function, but It will make the function to big.
so I thought one way for style implement like this.

```kotlin
verticalLayout {
    style<TextView> {   //no name style, apply to all the TextView
        textSize = xxxx
        textColor = xxxxx
    }
    style<TextView>("style1") {   //named style, apply to the TextView with style = "style1"
        textSize = xxxx
        textColor = xxxxx
    }
    editText {
        style = "style1"  //only apply style1 and no name style
    }.lparams(width = matchParent)

    view { 
        backgroundResource = R.color.color_f2 
    }.lparams(width = matchParent, height = 1)
    
    editText { // will only apply no name style
    }
}
```

I think this is possible by using view.tag

**Comment by Ribesg** [comment]
You're only styling TextViews in your applications?

**Comment by BennyWang** [comment]
sorry, I forget that style is a generic function, style<TextView>, so you can styling any View if you like

**Comment by BennyWang** [comment]
style\<TxtView\>

**Comment by yanex** [comment]
`View.setTag` should not be used in Anko because users should be able to use it directly.
Also, using text contacts (`"style1"`) is not the best practice as such constants can't be verified at compile-time.

What I recommend is to do this:
```kotlin
fun <T: View> makeStyle(style: T.() -> Unit) = { v : T -> v.style() }

class ExampleComponent : AnkoComponent<Context> {
    val buttonStyle = makeStyle<Button> {
        textColor = Color.CYAN
    }

    override fun createView(ui: AnkoContext<Context>) = ui.apply {
        button("Click me") {
            onClick { toast("Hello, world!") }
        }.apply(buttonStyle)
    }.view
}
```

**Comment by yanex** [comment]
FYI: `style()` was renamed to `applyRecursively()`.

**Comment by raveeshtech** [comment]
I have a question. what if I wanted to declare lparams on the layout as well as applyrecursively() on the same? Can I write as a fluentAPI?
