### ISSUE TITLE
Do not show views defined in Activity.onCreate

### ISSUE THREAD

**Issue by CodingPapi** [Kotlin/anko#137]
anko version is 0.8, 

I used anko to order a verticalLayout in onCreate, but it's not showing 

It is strange, cause I am told that setContentView will called by anko if I declare the view in onCreate
```
 class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
//        setContentView(R.layout.activity_main)

//        MyActivityUI().setContentView(this)
        toast("onCreate")

        verticalLayout {
            val name = editText()
            button("Say Hello") {
                onClick { ctx.toast("Hello, ${name.text}!") }
            }
        }
    }
```

but I define a AnkoComponent class and call AnkoComponent.setContent, it will render the view.

**Comment by CodingPapi** [comment]
but I just tried anko 0.7.2 is ok

**Comment by yanex** [comment]
Can you please try Anko 0.8.1?

**Comment by bfdeitch** [comment]
Anko 0.8.1 fixed this issue for me.
