### ISSUE TITLE
Rename gravity to explicit `layoutGravity` and `textGravity`

### ISSUE THREAD

**Issue by lukaspili** [Kotlin/anko#138]
Follow up of the issue #135 where the `gravity` property of the textview is shadowed by the one from the parent layout. 
I support the @Ribesg proposal about renaming the `gravity` property to something more explicit, like `layoutGravity` and `textGravity`.

**Comment by yanex** [comment]
Looks like the renaming is not needed anymore with the introducing of "DslMarker" support.
Please create the new issue if you still have the problem.
