### ISSUE TITLE
Kotlin 1.0 release

### ISSUE THREAD

**Issue by Ribesg** [Kotlin/anko#146]
https://gist.github.com/Ribesg/01d5ea2b81a0de564375

I was told this occurs because one of my Kotlin dependency was compiled with pre-1.0 Kotlin, and I only use Anko.

**Comment by Ribesg** [comment]
I'm able to reproduce this error in an emulator running Android 4.1. Only happens on Android 4.1, but 8.8% of every Android phones isn't nothing.

I tried to compile Anko myself using Kotlin 1.0, but the build process is a hell. Ant? Really?

**Comment by yanex** [comment]
Will be done tomorrow.

**Comment by yanex** [comment]
Done.
