### ISSUE TITLE
Lack of nullable values in anko-db

### ISSUE THREAD

**Issue by dstd** [Kotlin/anko#154]
It's not possible to pass null values into `insert`, `replace`, `update`, `where` and probably several other methods, because they use `Pair<String, Any>`. So there's no straight way to set some column to `null`. Probably they should use `Pair<String, Any?>` for values.

**Comment by PaulWoitaschek** [comment]
+1. 

Also the row parser throws an exception if a type is nullable and you specify it as nullable. Then it throws an exception that for example `Unit` cant be converted to `String?`.

**Comment by dstd** [comment]
[SqlParsers.kt](https://github.com/Kotlin/anko/blob/master/anko/library/static/sqlite/src/SqlParsers.kt#L176)
``` kotlin
private fun Cursor.getColumnValue(index: Int): Any? {
    if (isNull(index)) return null

    return when (getType(index)) {
        Cursor.FIELD_TYPE_INTEGER -> getLong(index)
        Cursor.FIELD_TYPE_FLOAT -> getDouble(index)
        Cursor.FIELD_TYPE_STRING -> getString(index)
        Cursor.FIELD_TYPE_BLOB -> getBlob(index)
        else -> Unit
    }
}
```
@yanex I'm not sure why `Unit` is used here. But if the column's value is `null`, then `getType` will not return a correct type, and this `Unit` will cause the `java.lang.ClassCastException` in `org.jetbrains.anko.db.rowParser.parseRow` (in generated SqlParserHelpers.kt).

In my project I made these null-safe wrappers to workaround this issue:
``` kotlin
fun Any.nonUnit() = if (this is Unit) null else this

fun <T1, T2, R> rowSafeParser(parser: (T1, T2) -> R): RowParser<R> {
    return object : RowParser<R> {
        override fun parseRow(columns: Array<Any>): R {
            if (columns.size != 2)
                throw SQLiteException("Invalid row: 2 columns required")
            @Suppress("UNCHECKED_CAST")
            return parser(columns[0].nonUnit() as T1, columns[1].nonUnit() as T2)
        }
    }
}
```
