### ISSUE TITLE
Rename layout not updated for synthetic imports

### ISSUE THREAD

**Issue by danielgomezrico** [Kotlin/anko#155]
Hi

if you have an old layout and a view with `kotlinx.android.synthetic` imports and then rename the `.xml` the new layout name is not in the path to import.

I have to clean, remove all build folders and restart `android studio` and then rebuild the project so I can import the new layout.

**Comment by yanex** [comment]
This issue is already fixed: https://youtrack.jetbrains.com/issue/KT-11944.
P.S.: Please use the main Kotlin issue tracker for bugs in Android Extensions.
