### ISSUE TITLE
Add Android's Support Library as a first class citizen on commons.

### ISSUE THREAD

**Issue by peleteiro** [Kotlin/anko#158]
Anko-common is the best Kotlin-Android lib available, and come times is only module of Anko you want to use. Having to get ``org.jetbrains.anko:anko-support-v4`,` witch comes with everything-anko, is not nice.

Please, consider adding Android's Support Library as a first class citizen on anko-commons.

Kotlin helps a lot:

```
import android.app.Fragment
import android.support.v4.app.Fragment as SupportFragment

inline fun <reified T: Service> Fragment.startService(vararg params: Pair<String, Any>) {
    AnkoInternals.internalStartService(activity, T::class.java, params)
}

inline fun <reified T: Service> SupportFragment.startService(vararg params: Pair<String, Any>) {
    AnkoInternals.internalStartService(activity, T::class.java, params)
}
```

I'm willing to send a pull request with it. But I need an ok to go.

**Comment by yanex** [comment]
`anko-common` should not be dependent on any of the support libraries Google provide.
What is possible is to create the new `anko-support-v4-common` and make the `anko-support-v4` artifact dependent on it.
