### ISSUE TITLE
async() not called on Android N Preview

### ISSUE THREAD

**Issue by Egorand** [Kotlin/anko#164]
I'm using the following setup:

**Android Studio version:** 2.1 Preview 4
**Kotlin version:** 1.0.1-1
**anko version:** 0.8.3
**compileSdkVersion:** 23
**targetSdkVersion:** 23
**minSdkVersion:** 15

And the following code:

``` kotlin
import android.os.Bundle
import android.support.v7.app.AppCompatActivity
import com.google.gson.Gson
import kotlinx.android.synthetic.main.activity_main.*
import org.jetbrains.anko.async
import org.jetbrains.anko.uiThread
import java.net.URL

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
    }

    override fun onResume() {
        super.onResume()
        loadTestData()
    }

    data class TestData(val userId: Int, val id: Int, val title: String, val body: String)

    private fun loadTestData() = async() {
        val dataStr = URL("http://jsonplaceholder.typicode.com/posts/1").readText()
        val data = Gson().fromJson(dataStr, TestData::class.java)
        uiThread {
            console.text = "${data.title}\n\n${data.body}"
        }
    }
}
```

When I'm running this code on an Android M emulator the data is loaded and displayed properly. However, when I run it on an Android N Preview emulator, the `async()` block never gets executed. Compiling against N version doesn't help as well.

Happy to provide any additional info if needed. Thanks!

**Comment by yanex** [comment]
Do you have any exceptions in logs? Looks like `readText()` failed to load the page content, and the default error handler in `async()` (or `doAsync()` now) is:

```kotlin
private val crashLogger = { throwable : Throwable -> throwable.printStackTrace() }
```

**Comment by 4u7** [comment]
Looks like this issue is obsolete and may be closed
