### ISSUE TITLE
Consider making listener methods inline

### ISSUE THREAD

**Issue by cypressious** [Kotlin/anko#174]
``` kotlin
fun android.view.View.onClick(l: (v: android.view.View?) -> Unit) {
    setOnClickListener(l)
}
```

will create an instance of `Function1` and an instance of `View.OnClickListener` that wraps it.

Consider changing it to 

``` kotlin
inline fun android.view.View.onClick(l: (v: android.view.View?) -> Unit) {
    setOnClickListener { l(it) }
}
```

**Comment by cypressious** [comment]
any progress on this?

**Comment by yanex** [comment]
Old listeners are made `inline` in 0.10.
The new listeners with coroutines can't be `inline` (inline suspend functions are not supported yet).
