### ISSUE TITLE
RecyclerView and ScrollBars

### ISSUE THREAD

**Issue by carmas123** [Kotlin/anko#179]
I've this situation in my code:

```
    override fun onCreateView(inflater: LayoutInflater?, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        return UI {
            verticalLayout {
                lparams(width = matchParent, height = matchParent)

                mList = recyclerView {
                    lparams(width = matchParent, height = matchParent)
                    leftPadding = dip(8)
                    rightPadding = dip(8)

                    val lm = LinearLayoutManager(ctx)
                    lm.isSmoothScrollbarEnabled = true
                    layoutManager = lm

                    setHasFixedSize(true)

                    addItemDecoration(HorizontalDividerItemDecoration.Builder(ctx).build())

                    isVerticalScrollBarEnabled = true
                    isScrollbarFadingEnabled = true


                }

            }
        }.view
    }
```

but I can't see the vertical scrollbar, basically without Anko I need to add scrollbars="vertical" in XML and all work. Now how can I do this with Anko?

**Comment by Ribesg** [comment]
See [this SO question](http://stackoverflow.com/questions/27056379/is-there-any-way-to-enable-scrollbars-for-recyclerview-in-code) and its answer.
> it seems to be impossible to enable scroll bars programmatically [on RecyclerViews]

**Comment by carmas123** [comment]
I do that, thank you so much

**Comment by kirillkh** [comment]
Note that this problem also exists with ListView and ScrollView. And there is a way to fix it without using XML layouts, see this answer: https://stackoverflow.com/a/41937476/3646645
