### ISSUE TITLE
textStyle and lineSpacingExtra

### ISSUE THREAD

**Issue by vlonjatg** [Kotlin/anko#188]
I'm experimenting with anko and while anko is great, I can't find two ```TextView``` attributes ```textStyle``` and ```lineSpacingExtra```. Any ideas how to implement them?

**Comment by carmas123** [comment]
You can use 

`setLineSpacing()`

**Comment by vlonjatg** [comment]
Yeah ```setLineSpacing()``` does it for the line height.

**Comment by takahawk** [comment]
Personally for me setting `typeface` instead of `textStyle` worked great. This question StackOverflow may be useful: http://stackoverflow.com/questions/7919173/android-set-textview-textstyle-programmatically
