### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by matthewdias** [Kotlin/anko#191]
I have a basic activity:
```
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?, persistentState: PersistableBundle?) {
        super.onCreate(savedInstanceState, persistentState)
        verticalLayout {
            padding = dip(100)
            button("test")
        }
    }

}
```
When I run it, there is no content. Any help?

**Comment by carmas123** [comment]
You can do (like documentation):
```
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?, persistentState: PersistableBundle?) {
        super.onCreate(savedInstanceState, persistentState)
        MainActivityUI().setContentView(this)
    }

  inner class MainActivityUI : AnkoComponent<AppCompatActivity> {
    override fun createView(ui: AnkoContext<AppCompatActivity>): View = with(ui) {
        verticalLayout {
            padding = dip(100)
            button("test")
        }
    }
  }
}
```

**Comment by matthewdias** [comment]
I tried that first, and it didn't work either.

**Comment by carmas123** [comment]
oh no...I try it and it's work fine check your code

**Comment by yanex** [comment]
@matthewdias What version of Anko do you use?

**Comment by matthewdias** [comment]
@yanex 0.8.3 for sdk21

**Comment by Ribesg** [comment]
There are so many reasons this may not work... What do you mean by "when I run it"? Are you sure you're recompiling everything and pushing it where you "run it"? Are you sure you run the right Activity?

**Comment by matthewdias** [comment]
This is after a full clean and build, and I only have one activity.

**Comment by scottmmjackson** [comment]
@matthewdias when you say "it doesn't work", there are so many things that could be going wrong. Is it failing to compile? Is it coming up blank on your emulator? Is it throwing an exception?

People seem to be having trouble replicating your issue, so you might want to see if you can describe some important details, like the structure of your project and the exact nature of the failure you're encountering.

**Comment by jonathanbergen** [comment]
I guess you are using the wrong `onCreate()` method.
You've overwritten `onCreate(Bundle savedInstanceState, PersistableBundle persistentState)` which only gets called 
>for those activities created with the attribute _android.R.attr.persistableMode_ set to _persistAcrossReboots_

Use `onCreate(Bundle savedInstanceState) ` instead.
