### ISSUE TITLE
Anko 0.9 beta1, DSL Preview Plugin

### ISSUE THREAD

**Issue by yanex** [Kotlin/anko#200]
[dsl-preview.zip](https://github.com/Kotlin/anko/files/282612/dsl-preview.zip)

**Comment by SupaHam** [comment]
At first it didn't work, but then I realised I needed to hit the refresh button in the UI (which refreshed gradle?) then it worked. Currently using Anko 0.8.3, works great! Thanks a bunch.

**Comment by yanex** [comment]
Because Anko DSL is just code in Kotlin, the build is required before the preview can be shown.
Try to use incremental compilation in Gradle (available in Kotlin 1.0.2), it works much faster with it. 👍

**Comment by Adambl4** [comment]
``` Android Studio 2.1.1 ```
``` compile 'org.jetbrains.anko:anko-sdk23:0.9-beta1'```
Got the error :
``` Rendering Problems The following classes could not be found:
- __anko.preview.View ```

**Comment by yanex** [comment]
@Adambl4 Can you provide a code fragment?

**Comment by Adambl4** [comment]
@yanex 
```
class NotificationsListUI : AnkoComponent<NotificationsList> {
    override fun createView(ui: AnkoContext<NotificationsList>) = with(ui) {
        textView {
            text = "test"
        }
    }
}
```

**Comment by scottmmjackson** [comment]
This is great! I was getting exceptions being thrown in the most recent repository version, but this seemed to clear them right up. I dropped a comment on the JB Plugins Repository pointing errant googlers here.

**Comment by niray** [comment]
I'm installed the v0.9 ,and click the refresh button ,but when builded finish ,
will display some wrong , that's the log ,please fix it.
`11:34:42 Plugin Error: Kotlin threw an uncaught IndexNotReadyException. Disable Plugin
11:34:42 IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation`

**Comment by LouisCAD** [comment]
@yanex Hi, could you clarify what is the file you attached in the first post and how to use it if it's what intended?

**Comment by OuSatoru** [comment]
Error with: com.intellij.diagnostic.PluginException: org/jetbrains/android/uipreview/AndroidLayoutPreviewToolWindowManager [Plugin: org.jetbrains.kotlin.android.dsl] when open a recent or start a new project when installed 0.9b, Android Studio 2.2.3

**Comment by chengxinping** [comment]
Cannot load project: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: org/jetbrains/android/uipreview/AndroidLayoutPreviewToolWindowManager [Plugin: org.jetbrains.kotlin.android.dsl]    when open an Android Project (0.9b android studio 2.2.3)

**Comment by yanex** [comment]
See also #314.

**Comment by gaojingwen945** [comment]
Always resulting in: Plugin Error: Anko Support threw an uncaught RuntimeException.
