### ISSUE TITLE
Anko DSL Preview for Android Studio 2.2

### ISSUE THREAD

**Issue by yanex** [Kotlin/anko#202]
The Layout Preview panel was completely changed in Android Studio 2.2, so the current DSL Preview plugin implementation became incompatible.

The sad fact is that all contributed hooks are gone. Moreover, the source code of Android Studio 2.2 is not available until release.

**Comment by niray** [comment]
`11:18:12 Plugin Error: Kotlin threw an uncaught IndexNotReadyException. Disable Plugin
11:18:12 IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation`

**Comment by revarnami** [comment]
I Cannot load project: 
com.intellij.ide .plugins.PluginManager$StartupAbortedException:
com.intellij.diagnostic.PluginException:
org/jetbrains/android/uipreview/AndroidLayoutPreviewToolWindowManager
[Plugin: org.jetbrain.kotlin.android.dsl]

**Comment by IgorGee** [comment]
I'm getting the same error as @revarnami

**Comment by niilante** [comment]
Sup Guys
 Any one with a fix cause I have a same problem with my view. Android studio threw me this:

Cannot load project: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: org/jetbrains/android/uipreview/AndroidLayoutPreviewToolWindowManager [Plugin: org.jetbrains.kotlin.android.dsl]

**Comment by dave08** [comment]
Same with me, I can't even open the IDE as long as the plugin is enabled...

**Comment by Hesamedin** [comment]
I just upgraded my AndroidStudio on stable channel and got this error. any solution/workaround?

**Comment by yanex** [comment]
@Hesamedin Unfortunately, DSL Preview plugin is not available for AS 2.2 yet, sorry. We will try to fix this as early as possible, but for now the only possible way is to use AS 2.1 or IntelliJ IDEA.

**Comment by faith-hb** [comment]
解决办法：将anko插件卸载掉就可以了；

**Comment by Hesamedin** [comment]
I just deleted Anko DSL plugin and AS 2.2 could start without problem.

**Comment by baghad** [comment]
I just deleted Anko DSL plugin and AS 2.2 could start without problem.

Hesamedin : this is ok , thanks verymacth

**Comment by Edward608** [comment]
I hope the Anko team can fix this problem ASAP as this is one of the main feature of anko, without the preview its quite hard to use Anko to build layouts

**Comment by BukT0p** [comment]
Still there, AndroidStudio 2.2.1. Anko version 0.9

**Comment by SuhairZain** [comment]
@yanex Hi, any updates on this issue? I'm having a bit of a trouble designing layouts without a preview. Any workaround other than downgrading to AS 2.1?

**Comment by LouisCAD** [comment]
Hi,
I'm going to do a talk about Kotlin for Android Development, in which I'll cover anko in 2017, February. Using anko without layout preview is almost a show stopper. Is there any chance this can be working again by the end of 2017, January?

**Comment by yousuf-haque** [comment]
> We will try to fix this as early as possible, but for now the only possible way is to use AS 2.1 or IntelliJ IDEA.

Hey I'm using intellij ultimate 2016.3 and can't seem to get this to work. Any tips?

**Comment by piotrek1543** [comment]
@yousuf-haque nope as well with Android Studio 2.2.1

**Comment by sindrenm** [comment]
@LouisCAD: Funny, I'm doing the exact same thing, February 2nd, 2017. Was also hoping to have this fixed by then. It's a bit annoying to have to first create an XML layout for the preview and then convert to Anko DSL.

**Comment by LouisCAD** [comment]
@sindrenm I personally gave up using Anko for now, because writing xml is more convenient with the preview, and the fact that I'm more used to it. Still looking forward anko preview support comeback though.

**Comment by krokofant** [comment]
Sad to see that this has been broken for so long and that support is only for legacy versions. I got my hopes up from reading the documentation. 😬

**Comment by pinkApple** [comment]
I also got this error until  uninstalled anko plugin, any other way to solve this problem?

**Comment by sindrenm** [comment]
@pinkApple: Not right now. The plugin doesn't support newer versions of Android Studio.

**Comment by stackprogramer** [comment]
when i update android studio 👍 
it returns this errors and can not open android project
Cannot load project: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: com/android/builder/model/BaseArtifact [Plugin: org.jetbrains.android]

**Comment by sindrenm** [comment]
@stackprogramer: You will need to disable the Anko DSL Preview plugin, as mentioned above.

Configure → Settings → Plugins → Anko DSL Preview (untick the checkbox to the right)

**Comment by haydenholligan** [comment]
Is there an update on the progress of this?

**Comment by stackprogramer** [comment]
i did this,error not fix finally i uninstalled and i downloaded most update  stable android studio thanks

**Comment by Prokky** [comment]
Any update on this bug?

**Comment by twero** [comment]
I am now trying to update!
because i am also having this kind of error!

**Comment by MewX** [comment]
@twero You should downdate :-(

**Comment by xavier-fernandez** [comment]
+1, this issue blocks our team to use Anko... :(

**Comment by twero** [comment]
i already okay with this
i noticed error was gone

**Comment by LouisCAD** [comment]
@twero Which error which was gone, where? Could you elaborate please?

**Comment by glnix** [comment]
+1
AS 2.2.3
Andko Preview Plugin 0.9b

**Comment by yanex** [comment]
See also #314.

**Comment by dEn13L** [comment]
The problem still here

Android Studio 2.3 Beta 4
Build #AI-162.3715353, built on February 8, 2017
JRE: 1.8.0_112-release-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Anko DSL Preview 0.9b

**Comment by tmseiler** [comment]
Just encountered this myself.

**Comment by krokofant** [comment]
@tmseiler There is a new issue for all these related issues, check #314

**Comment by zhiqizhu** [comment]
Any update?

**Comment by trubitsyn** [comment]
Still there with AS 2.3.3, Anko DSL Preview 0.9b

**Comment by krokofant** [comment]
@trubitsyn It's already been out a while.

**Comment by trubitsyn** [comment]
Unfortunately 0.10.1 is not available through AS plugin installer yet.

**Comment by kevinvanmierlo** [comment]
It says in the [wiki](https://github.com/Kotlin/anko/wiki/Anko-Layouts#anko-support-plugin): 

> The Anko Support plugin is currently supported only in Android Studio 2.4+.

The stable version is at 2.3.0 right now. So it probably only works with the canary version. Which is 3.0 canary 5.

**Comment by Aheadboy** [comment]
plugin can not use in IntelliJ IDEA  too @yanex 171.46....
