### ISSUE TITLE
Proposal: Toast like helpers for Snackbar

### ISSUE THREAD

**Issue by rakshakhegde** [Kotlin/anko#203]
Snackbar helpers are not present in Anko Design Lib like there is for Toast and I would like add that and do a PR. Shall I go ahead?

**Comment by yanex** [comment]
Yes, sure.

**Comment by BryanJBryce** [comment]
@rakshakhegde Whats the status on this?

**Comment by yanex** [comment]
@BryanJBryce Snackbar extensions will be added in Anko 0.10.

**Comment by AdamRoweSys** [comment]
Has anyone been able to use this yet? I'm getting unresolved reference using anko version 0.10.1

**Comment by jorgegil96** [comment]
@AdamRoweSys Make sure you have `compile "org.jetbrains.anko:anko-design:$anko_version"` in your dependencies

**Comment by AdamRoweSys** [comment]
@jorgegil96 Yeah, I was using the meta-dependency `compile "org.jetbrains.anko:anko:$anko_version"` not realizing the design components were separate. Thanks!
