### ISSUE TITLE
android.support.design.widget.TextInputEditText

### ISSUE THREAD

**Issue by abond** [Kotlin/anko#205]
Hello!

Please, add this widget to your DSL.

Thanks!

**Comment by yaymalaga** [comment]
Now, with the new com.android.support:design:24.2.0 library, apps force close: java.lang.ClassCastException: android.widget.EditText cannot be cast to android.support.design.widget.TextInputEditText

Any workaround to use before TextInputEditText is added in anko?

**Comment by abond** [comment]
Define this somewhere:

```
inline fun ViewManager.textInputEditText() = textInputEditText {}
inline fun ViewManager.textInputEditText(theme: Int = 0, init: TextInputEditText.() -> Unit) = ankoView({ TextInputEditText(it) }, theme, init)
```

**Comment by yaymalaga** [comment]
@abond working perfectly, thanks for the help!

**Comment by Rahulkr2** [comment]
@abond Could you please elaborate ?  Why does this work ?

**Comment by abond** [comment]
@Rahulkr2 The principles of building DSL's in Kotlin well described in this article https://kotlinlang.org/docs/reference/type-safe-builders.html. 
Reading it should help you understand how Anko DSL works.

**Comment by megifernanda** [comment]
how to make XML android.support.design.widget.TextInputEditText in kotlin?
