### ISSUE TITLE
Memory leaking when using textChangedListener

### ISSUE THREAD

**Issue by squeezymo** [Kotlin/anko#208]
I use Anko in my project together with [LeakCanary](https://github.com/square/leakcanary), a library for detecting memory leaks. I have a simple scenario where user opens a fragment, fills some text fields in it, saves the result and returns to the previous screen (with `popBackStack()`).

To bind the content of an `EditText` to my model, I use `textChangedListener`. The problem is, oftentimes when I return back and the fragment is supposed to be destoyed, LeakCanary reports that it's leaked by `AnkoContextImpl.owner`. Looks like what is actually being leaked is a view created by Anko.

I have created a small project to reproduce this behavior. I may be missing something but the app seems to be simple enough. I would really appreciate it if anyone could take a look at it and tell me if I'm doing something wrong.

[Project](https://github.com/squeezymo/MemoryLeakExample)
[LeakCanary log](https://gist.github.com/squeezymo/c96358e9e86ba591933892d8c0d7ab07)

Steps to reproduce (I used API 22):
- Click "Open Fragment B",
- Enter some text and click toolbar menu item,
- Wait for a while for LeakCanary to dump memory and see notification.

**Comment by yanex** [comment]
Looks like this is a well-known problem and it's unrelated to Anko:

http://stackoverflow.com/questions/34631818/leakcanary-report-leak-in-inputmethodmanager.
https://code.google.com/p/android/issues/detail?id=34731

**Comment by squeezymo** [comment]
Indeed, I missed it somehow. Also, it does not reproduce on Android M.
Thanks.
