### ISSUE TITLE
Support ConstraintLayout in Anko

### ISSUE THREAD

**Issue by yanex** [Kotlin/anko#210]

**Comment by seaskyways** [comment]
What is the progress of this ?

**Comment by rostopira** [comment]
Since PercentLayout is deprecated now, will ConstraintLayout be supported soon?

> The support-percent module has been deprecated. Clients of this module should migrate to the new ConstraintLayout widget

https://developer.android.com/topic/libraries/support-library/revisions.html

**Comment by ngreduce** [comment]
@seaskyways @rostopira check https://github.com/ngreduce/anko-constraint-layout for now. It is not final implementation and needs some helpers, but it worked for me.

**Comment by guoyingtao** [comment]
I want to know the progress too.

**Comment by Lakedaemon** [comment]
I'm considering using anko for my next project, but this issue worries me.

At the moment, is it possible to embed a ConstraintLayout inflated through xml in a view built with anko ?
Are there trade off ?

**Comment by ngreduce** [comment]
yes, it should be possible to inflate. But from my little experience it is better to stick with standard layouts for now. Anko feels like is not complete in term of designer and different configurations. But you can mix both approaches at some extent.

**Comment by GrzegorzDyrda** [comment]
Any update on this?

**Comment by ngreduce** [comment]
I think project is almost dead. Maybe maintainer is busy on other tasks

**Comment by kuhnroyal** [comment]
@spkingr At the moment you need to checkout my fork and build it yourself. I am not sure when and if this will get merged. But I am sure people testing it will help.

**Comment by spkingr** [comment]
@kuhnroyal I will try, thank you!

**Comment by Antimonit** [comment]
Hi guys. I really liked using the constraint layout but also using Anko for building stuff. The two are not compatible with each other, so I decided to make a library ^_^

[https://github.com/AckeeCZ/anko-constraint-layout](https://github.com/AckeeCZ/anko-constraint-layout)

It is a bigger project than I originally intended. It adds custom DSL specifically made for use with constraint layout and other stuff like automatic generation of ids for views. Readme should be explanatory enough.
We use it in our company for new projects and so far everyone is happy with it. Hopefully, it will be useful for others as well.

**Comment by kirillkh** [comment]
@4u7 Kudos for making this happen!

**Comment by kuhnroyal** [comment]
Yes, I just replaced my code from the PR with the 0.10.4. Works like a charm!
