### ISSUE TITLE
alert builder is private

### ISSUE THREAD

**Issue by westito** [Kotlin/anko#215]
In the latest version I can't access DialogBuilder (alert {}.builder). I rely on this method before to manipulate the dialog before show. Please bring it back. Or add a build() function:
`fun build(): AlertDialog {
        checkBuilder()
        dialog = builder!!.create()
        builder = null
        return dialog!!
    }`

**Comment by alan-rodriguez** [comment]
My project is not using the DSL features of Anko (yet). Being able to access `builder: AlertDialog.Builder?` was important because it let me call `AlertDialog.Builder.setView(int layoutResId)` when creating dialogs with custom layouts.

**Comment by rostopira** [comment]
#333

**Comment by yanex** [comment]
The `build()` method is added to the new `AlertBuilder` interface.
