### ISSUE TITLE
Not able to set lparams on cardView

### ISSUE THREAD

**Issue by kiangtengl** [Kotlin/anko#216]
I'm new to anko, but so far I've not been able to find a way to set layout parameters on a cardView.

i.e.

```
cardView {

}.lparams { // lparams does not exist on cardView
    margin = dip(5) 
}
```

**Comment by Anthonyeef** [comment]
@kiangtengl 
`lparams` should be wrap under `layout`. You can apply `lparams` method to whatever view you want.
For example:

```Kotlin
textView {
xxx
}.lparams {
xxx
}
```
This won't work.

While try to wrap this textView under linearLayout:

```Kotlin
linearLayout {
   lparams {
      width = wrapContent
      height = wrapContent
    }
    textView {
    xxxx
    }.lparams {
    width = matchParent
    height = wrapContent
    }
}
```

This should work.
