### ISSUE TITLE
No virtual method setForeground

### ISSUE THREAD

**Issue by abond** [Kotlin/anko#220]
java.lang.NoSuchMethodError: No virtual method setForeground(Landroid/graphics/drawable/Drawable;)V in class Lorg/jetbrains/anko/_LinearLayout; or its super classes 

Same error for org/jetbrains/anko/appcompat/v7/_LinearLayoutCompat.

Error appears on API level 21. On API 23 everything works fine. 
In XML layouts everything works on both API levels.
As I understand setForeground available from API lvl 1.

**Comment by abond** [comment]
Find out that it is official android documentation error. 
The method introduced in API lvl 23 View.setForegroud, is reported to be API level 1 on the Android Developer Guide.

**Comment by yanex** [comment]
So I think the issue can be closed? :)

**Comment by abond** [comment]
Ofcourse😃
