### ISSUE TITLE
Cleaner dip usage

### ISSUE THREAD

**Issue by nitrico** [Kotlin/anko#222]
[Here](https://github.com/Kotlin/anko/blob/master/anko/library/static/common/src/Dimensions.kt), I would replace 

``` kotlin
fun Context.dip(value: Int): Int = (value * resources.displayMetrics.density).toInt()
fun Context.dip(value: Float): Int = (value * resources.displayMetrics.density).toInt()
```

with:

``` kotlin
val Int.dp: Int 
    get() = (this * Resources.getSystem().displayMetrics.density + 0.5f).toInt()

val Float.dp: Int 
    get() = (this * Resources.getSystem().displayMetrics.density + 0.5f).toInt()
```

Usage then would be cleaner, for example:

``` kotlin
// before:
view.setPadding(ctx.dip(8), ctx.dip(16), ctx.dip(8), ctx.dp(16))

// after:
view.setPadding(8.dp, 16.dp, 8.dp, 16.dp)
```

It looks like you are adding the "units".
I'm using it in my projects and works fine.

What do you think?

**Comment by yanex** [comment]
`getSystem()` returns 

> a global shared Resources object that provides access to only system resources (no application resources), and is not configured for the current screen (can not use dimension units, does not change based on orientation, etc),

so it is very questionable if it can be used.

**Comment by kevinmost** [comment]
I agree it is annoying to have to have the `Context` and `value` involved every time you want to convert pixels to dps, but as @yanex pointed out, `getSystem()` is definitely unsafe, considering that multi-screen is a possibility.

How about some sort of DSL for this?

```kotlin
inline fun Context.dips(block: DipsContext.() -> Unit) {
  DipsContext(this).apply(block)
}

class DipsContext(context: Context) {
  private val density = context.resources.displayMetrics.density
  
  val Int.dp: Int
    get() = (this * density).toInt()
  
}
```

Usage would be:

```kotlin
context.dips {
  8.dp.let { view.setPadding(it, it, it, it) }
}
```

Similar extensions would be nice to have for sp and things like that of course.

**Comment by yanex** [comment]
Here we create a new instance of `DipsContext` each time we want to write something like `8.dip`, and it looks like nothing but a memory waste.

In theory, such extension properties can be added to `AnkoContext`, in which we have access to the `Context` instance.

Is the `8.dip` syntax significantly better than the `dip(8)`? The latter couldn't be deprecated anyway (`AnkoContext` is not available everywhere), so we would have two different syntaxes for doing exactly the same. As for me it smells.
