### ISSUE TITLE
imageButton DSL compatibility broken

### ISSUE THREAD

**Issue by jsnowacki** [Kotlin/anko#224]
I recently switched my project to Anko 0.9 and noticed that the `imageButton` was created but without any image. It came out that while the call `imageButton(R.drawable.ic_camera_alt_24dp)` worked fine in 0.8.3 and also created button without any complains, but in 0.9 the image was not rendering as the argument was treated as theme; see `Views.kt` `imageButton` functions. To fix that we need to either specify resource as e.g. `imageButton(imageResource = R.drawable.ic_camera_alt_24dp)` or pass the second theme argument e. g. `imageButton(R.drawable.ic_camera_alt_24dp, 0)`. 

The main issue is that I had no indication of this change and the code was compiling fine, so it took me a bit to notice the invalid call with resource Id as theme.

Cheers,

Jakub

**Comment by yanex** [comment]
The bug is fixed in 0.10: all block functions that accept a `theme` parameter are now renamed to "themed…()" (e.g. `themedImageButton()`).
