### ISSUE TITLE
Sqlite in-memory database

### ISSUE THREAD

**Issue by Gorita** [Kotlin/anko#226]
https://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper.html
>Public constructors
>...
>name	String: of the database file, or null for an in-memory database

how about ```ManagedSQLiteOpenHelper```'s parameter ```name: String``` allows null?

**Comment by Gorita** [comment]
I opened a pull request #228 

I hope it would be merged 😃

**Comment by yanex** [comment]
Fixed.
