### ISSUE TITLE
README Version Badge is incorrect

### ISSUE THREAD

**Issue by aaboyd** [Kotlin/anko#227]
In the README.md it says 0.8.3 is the current version.

Would there be any objections to using the bintray version badge instead of the badge.fury.io one?

```
[ ![Download](https://api.bintray.com/packages/jetbrains/anko/anko/images/download.svg) ](https://bintray.com/jetbrains/anko/anko/_latestVersion)
```
[ ![Download](https://api.bintray.com/packages/jetbrains/anko/anko/images/download.svg) ](https://bintray.com/jetbrains/anko/anko/_latestVersion)

**Comment by yanex** [comment]
Fixed. Thank you!
