### ISSUE TITLE
RelativeLayout.LayoutParams not applying when using View-parameter method overloads

### ISSUE THREAD

**Issue by maroselo** [Kotlin/anko#232]
Hi, I am currently trying anko's power within small Android project and I have found strange behavior. It occurres when using the `relativeLayout {...}`. Here is the code:
```kotlin
relativeLayout {
    padding = dip(16)
    time = textView {
        text = "59:59:59"
        textSize = 40f
    }.lparams {
        alignParentTop()
        centerHorizontally()
    }
    startPause = button("start").lparams {
        below(time)
        centerHorizontally()
    }
    reset = button("reset").lparams {
        below(startPause)
        centerHorizontally()
    }
}
```
where `time`, `startPause`, `reset` are `lateinit var`s declared at `Activity` top level.
The code above produces the following output:
![wrong](https://cloud.githubusercontent.com/assets/9325961/17495660/4d1c9682-5dba-11e6-8eb5-a97cf836b57e.png)
However, when I add `id` properties to each view above and I __leave__ the `below()` function __as is__ (with a parameter of the type `View`), it now works fine as you can see here:
![correct](https://cloud.githubusercontent.com/assets/9325961/17495829/e24a307a-5dba-11e6-948b-295a987ea19d.png)

Is this the correct behavior or is it a bug?

Thanks for answers.

**Comment by fboldog** [comment]
This is the correct behaviour because view must have id if you would like use in this case.
Related code:
https://github.com/Kotlin/anko/blob/master/anko/library/static/common/src/RelativeLayoutLayoutParamsHelpers.kt#L43

**Comment by maroselo** [comment]
Oh, thanks for the explanation. 

I am closing the issue.
