### ISSUE TITLE
outside layoutParams

### ISSUE THREAD

**Issue by yoavst** [Kotlin/anko#24]
Let's said I want to make a a listview item with a fixed size. In order to do that with anko I need to put it inside another ViewGroup.

**Comment by yanex** [comment]
Can you provide an example, please?

**Comment by yoavst** [comment]
https://github.com/yoavst/ohelshem/blob/master/app/src/main/res/layout/lesson_view.xml
I want to make a recyclerView of those item. It is impossible currently since you cannot put layoutParams to the outside viewgroup.

**Comment by yanex** [comment]
You can always put it explicitly by setting the `layoutParams` property.
Please create the new issue if it is unacceptable for you for some reason.
