### ISSUE TITLE
why async must use async() {...} or async(fun...), but not async {...}?

### ISSUE THREAD

**Issue by yybear** [Kotlin/anko#244]
i thought i can use like:
`
private fun updateTime() = async {
        while (true) {
            val time = sdf.format(Date())
            uiThread {
                timeText.text = time
            }

            Thread.sleep(10000)
        }
    }
`

but androidstuio gave me an error: Unsupported [async block/lambda... use async() {...} or async(fun...)
i am studying kotlin,  i think i can use like async {...}
i really want to know the reason. anyone can help?
thanks!

**Comment by Jamefrus** [comment]
May'be `async` reserved as keyword.

**Comment by yybear** [comment]
hi @Jamefrus , here is the async:

fun <T> T.async(task: AnkoAsyncContext<T>.() -> Unit): Future<Unit> {
    val context = AnkoAsyncContext(WeakReference(this))
    return BackgroundExecutor.submit { context.task() }
}
from anko-common-0.8.3-sources.jar!\org\jetbrains\anko\Async.kt

i think it's just a fun.

**Comment by yybear** [comment]
it's really strange. in anko-common-0.8.3-sources.jar!\org\jetbrains\anko\Async.kt, there is another fun asyncResult:

`fun <T, R> T.asyncResult(task: AnkoAsyncContext<T>.() -> R): Future<R> {`
    `val context = AnkoAsyncContext(WeakReference(this))`
    `return BackgroundExecutor.submit { context.task() }`
`}`

it can be used like asyncResult {...}
so async is really special, but we don't know the reason.

**Comment by yybear** [comment]
@Jamefrus  u r right, [http://stackoverflow.com/questions/34803897/what-are-the-reserved-keywords-in-kotlin](url)

thanks!

**Comment by dstd** [comment]
and it was replaced with `doAsync` in the latest release
