### ISSUE TITLE
org.jetbrains.anko.AnkoException: 'android.widget.TextView.enabled' property does not have a getter

### ISSUE THREAD

**Issue by deadmoto** [Kotlin/anko#245]
Here is a snippet:

```
textView() {
    onClick {
        if (enabled) {
        }
    }
}
```

When I run this code I get an exception:
org.jetbrains.anko.AnkoException: 'android.widget.TextView.enabled' property does not have a getter

Changing 'enabled' to 'isEnabled' fixes the problem.

**Comment by yanex** [comment]
Solution: do not generate `TextView.enabled`.
