### ISSUE TITLE
Helper functions for EditText

### ISSUE THREAD

**Issue by yanex** [Kotlin/anko#25]
Helper functions, such as `passwordEditText()` are required so one doesn't need to specify an `InputType` exactly.

**Comment by phajduk** [comment]
Hi @yanex, I would like to implement this enhancement. Could you advise me if following solution would be OK?
```  kotlin
[suppress("NOTHING_TO_INLINE")]
public inline fun ViewManager.passwordEditText(): android.widget.EditText = passwordEditText({})
public inline fun ViewManager.passwordEditText(inlineOptions(InlineOption.ONLY_LOCAL_RETURN) init: android.widget.EditText.() -> Unit): android.widget.EditText = addView {
    ctx ->
    val view = android.widget.EditText(ctx)
    view.setInputType(InputType.TYPE_CLASS_TEXT or InputType.TYPE_TEXT_VARIATION_PASSWORD)
    view.init()
    view
}
```

I'm not sure if DSL generator could be used to auto-generate it. I suppose more methods like above one needs to be implemented by hand e.g. ```numberEditText()```, ```phoneEditText()``` etc.

**Comment by yanex** [comment]
@phajduk Hello! Code is ok!

I moved all custom widgets to [OtherWidgets.kt](https://github.com/JetBrains/anko/blob/master/dsl/static/src/OtherWidgets.kt) file. You can add all new widgets there; if it is not a container like `verticalLayout()`, an extension function for `ViewManager` would be pretty enough.

`EditText` actually has lots of input types, such as person name or a signed number. Probably, it's better to have a single `editText(format: TextFormat, ...)` and a `enum class TextFormat`, so one could write something like this:

```kotlin
editText(InputConstraints.NUMBER, "12345")
```

Though, the `TextFormat` name is discussable.
