### ISSUE TITLE
Workaround to use RelativeLayout positioning without ids

### ISSUE THREAD

**Issue by SuhairZain** [Kotlin/anko#270]
Hi,
I was trying to recreate an XML view using Anko and I came across this issue wherein if I assign a view to a val and try to position a view relative to it, it doesn't work. But when I assign an id to the view and try to position relative to the id, it works. The way I understand it, Anko uses the view's id to do the positioning as evident from this line:
`inline fun LayoutParams.below(view: View): Unit = addRule(BELOW, view.id)`(https://github.com/Kotlin/anko/blob/master/anko/library/static/common/src/RelativeLayoutLayoutParamsHelpers.kt#L43)

As evident from the issue [232](https://github.com/Kotlin/anko/issues/232), this is the expected behavior. I was wondering if there was a way I could make this work without setting the ids. It could be something as simple as checking if the passed view has an id set and if not, creating one before trying to access the id. I'd be happy to submit a PR for the same if you think it could be added to Anko. Please advice.

**Comment by neverwoodsS** [comment]
I meet this trouble too. My solution is below, it works any way :) 

fun RelativeLayout.LayoutParams.aboveOf(v: View) {
    v.checkId()
    addRule(RelativeLayout.ABOVE, v.id)
}

fun RelativeLayout.LayoutParams.belowOf(v: View) {
    v.checkId()
    addRule(RelativeLayout.BELOW, v.id)
}

fun RelativeLayout.LayoutParams.leftOf(v: View) {
    v.checkId()
    addRule(RelativeLayout.LEFT_OF, v.id)
}

fun RelativeLayout.LayoutParams.rightOf(v: View) {
    v.checkId()
    addRule(RelativeLayout.RIGHT_OF, v.id)
}

fun RelativeLayout.LayoutParams.sameLeftWith(v: View) {
    v.checkId()
    addRule(RelativeLayout.ALIGN_LEFT, v.id)
}

fun RelativeLayout.LayoutParams.sameRightWith(v: View) {
    v.checkId()
    addRule(RelativeLayout.ALIGN_RIGHT, v.id)
}

fun View.checkId() {
    if (id <= 0) {
        addRandomId()
    }
}

fun View.addRandomId() {
    id = Random().nextInt(99999999)
}

**Comment by SuhairZain** [comment]
@neverwoodsS 
That's a good workaround. I was thinking of doing a PR to make Anko generate an id by default if it's not already set. I haven't received any comment on it so far. Think I'll go ahead and do it anyway.

**Comment by charleskorn** [comment]
Perhaps at the very least all of the different layout rule methods (`leftOf`, `rightOf` etc.) can check the ID and throw an exception or log a warning if it is not set? I spent 20 minutes trying to work out why my layout wasn't being applied and there was nothing obviously wrong - until I realised that I needed to set the ID.

**Comment by rostopira** [comment]
I'm doing it like that

```
relativeLayout {
    val t = textView("Hello!")
    button("Hi!").lparams { below(t) }
}
```

**Comment by mradzinski** [comment]
I was about to give up on this already... Pretty weird and flawed to offer an overloaded method which doesn't take effect unless another condition is met. I'm with @charleskorn that an exception should be thrown letting the developer know that ```below(view)``` doesn't work unless the view you are using as reference has an id.

**Comment by yanex** [comment]
Unfortunately, `RelativeLayout` does not provide the functionality. Maybe it can be solved with some custom layout (`RelativeLayout` fork?).
Anyway, I opened the new issue (#270) about throwing `Exceptions` on using `leftOf()`, `rightOf()`, ... functions on views without the `id` being set.
