### ISSUE TITLE
non-android-specific extensions in Collections.kt and Arrays.kt

### ISSUE THREAD

**Issue by caplan** [Kotlin/anko#277]
Just curious, why are there non-android-specific extensions in anko (I mean vs. putting them in kotlin stdlib)? For example `List.forEachByIndex()`.

**Comment by yanex** [comment]
On the desktop JDK, an iterator initiating is very cheap, and for the numerous reasons using indices is considered a bad practice. But Android is another story: its virtual machine is not smart enough to optimize the code with iterators, so it's quite common to iterate with the index variable.
