### ISSUE TITLE
View.backgroundDrawable method in CustomViewProperties is deprecated in Android SDK code

### ISSUE THREAD

**Issue by Anthonyeef** [Kotlin/anko#278]
I noticed that in `CustomViewProperties.kt`, `View.backgroundDrawable` actually will call `setBackgroundDrawable()` method in Android SDK code `View.java` Line 17228:

```Java
/**
  * @deprecated use {@link #setBackground(Drawable)} instead
  */
  @Deprecated
 public void setBackgroundDrawable(Drawable background) {
      computeOpaqueFlags();

      if (background == mBackground) {
          return;
      }
( also some other code...)
```

It's annotated as `Deprecated` and maybe it's better to use `setBackground(Drawable drawable)` method instead.

**Comment by yanex** [comment]
`setBackground(Drawable)` is available since API level 16. Anko currently supports API level 15.
