### ISSUE TITLE
Fragment extension functions are not defined for support Fragment

### ISSUE THREAD

**Issue by SalomonBrys** [Kotlin/anko#28]
In Anko 0.6-15, I can find no extension method whatsoever that apply to `android.support.v4.app.Fragment`.

Any plan to support support fragments ?

**Comment by yanex** [comment]
Versions `0.6-15s` and `0.6-19s` include functions and properties for `support-v4` and `appcompat-v7` libraries as well.

**Comment by SalomonBrys** [comment]
OK, if I understand correctly, the 15 and 19 are the SDK level, and the s is for support. Is that right ?

**Comment by yanex** [comment]
Yes, that's right.

**Comment by damianpetla** [comment]
Maybe its a stupid question but it's not clear for me when should I use `0.6-15s` and when `0.6-19s`? I have minSdk = 16 in my project and I use support library.

**Comment by SalomonBrys** [comment]
A diff between `anko-0.6-15-sources.jar` and `anko-0.6-19-sources.jar` shows:

* A lot of difference in `InterfaceWorkarounds.java` that I don't understand.
* Adding support for creating `LayoutParams` by copy, which is a feature that came with SDK 19
* Addition of listener builder methods:
    -  `AutoCompleteTextView.onDismiss` for the `AutoCompleteTextView.OnDismissListener` that came with SDK 17
    - `VideoView.onInfo` for the `MediaPlayer.OnInfoListener` that came with SDK... 3! So I don't understand why it is in -19 and not in -15.
* Lots of additions for all the view getters, setters and methods that came after SDK 15
* Access to all services that were added after SDK 15 such as `BLUETOOTH_SERVICE`, `PRINT_SERVICE`, etc.

What I don't understand is why creating two libraries, You can use the -19 library with your app without problems *as long as* you are not using functions that refer to features that are over SDK 16.
So why two library ? And why specifically SDK 15 and 19 ?

**Comment by yanex** [comment]
Related issue: #58.
