### ISSUE TITLE
Infinite build RxAndroid2

### ISSUE THREAD

**Issue by arvabalazs** [Kotlin/anko#289]
Hello

If both of 
`compile 'org.jetbrains.anko:anko-sdk19:0.9' // sdk19, sdk21, sdk23 are also available`
and
`compile 'io.reactivex.rxjava2:rxandroid:2.0.1'`
`compile 'io.reactivex.rxjava2:rxjava:2.0.1'`
are enabled in project gradle file, the build goes into an infinite loop.

Android Studio version: 2.2.3 (older version also affected)
Kotlin version: 1.0.6 (older version also affected)
Gradle version: 2.2.3

RxAndroid1 versions works fine, currently this issue is blocking me to upgrade to 2.x.

Can you check the issue? Do you need more information?

UPDATE
It looks like the adding RxJava beside anko is enough for a repro.

Thank you,
Balazs

**Comment by yanex** [comment]
I can't reproduce the bug (Kotlin 1.0.5-2 or 1.1-rc-86 from https://bintray.com/kotlin/kotlin-dev, Gradle 2.14.1, Android Gradle plugin 2.2.1). Can you provide some more information about your Gradle setup?

**Comment by arvabalazs** [comment]
It is weird:
1. It was still there
2. I narrowed the problem to 3 source file. Every of them contains direct Anko-Rx integrations
3. I have commented out the integrations and make the whole project buildable (fixed every import and others)
4. When it compiled successfully, I try to turn on the suspicious section, and suprisingly immediatelly worked.

This issue may affect only code bases where one try to migrate from 1.x to 2.x AND there is direct integration between those libs.

However, I solved the 'issue'. So if you want you can close the ticket. Thank you

**Comment by yanex** [comment]
This sounds like an error in kotlinc. If you are still able to reproduce the issue, can you please share the example project?

**Comment by yanex** [comment]
The issue is closed because of no response. Please file the new issue if the problem still exists.
