### ISSUE TITLE
Can't pass params to intentFor when using support library Fragment

### ISSUE THREAD

**Issue by mattyway** [Kotlin/anko#292]
The [intentFor extension method](https://github.com/Kotlin/anko/blob/d1cb92a723b70d8052de20754d2adc2168dd3d81/anko/library/static/supportV4/src/SupportIntents.kt#L48) on the support library Fragment class doesn't have the same signature as the [one](https://github.com/Kotlin/anko/blob/d1cb92a723b70d8052de20754d2adc2168dd3d81/anko/library/static/common/src/Intents.kt#L69) on the regular Fragment class. It is missing the params argument. 

The missing params argument means that `intentFor<MyActivity>("myId" to 42)` doesn't compile when inside of a support Fragment.

**Comment by akamuza** [comment]
I still have the same issue. version 0.10.4
