### ISSUE TITLE
Anko DSL Preview Plugin can not work in androidStudo 2.2.3

### ISSUE THREAD

**Issue by s949492225** [Kotlin/anko#293]
![image](https://cloud.githubusercontent.com/assets/7496283/21604784/23f4d0f4-d1e0-11e6-8b1e-9da8b46a18c4.png)

**Comment by pinkApple** [comment]
not support 2.2.3, you should disable the plugin.

**Comment by bentolor** [comment]
Duplicate of #202

**Comment by blazeur** [comment]
Hi,
I have the same problem on Android 2.3 with anko 0.9b.
I don't find issue

**Comment by piotrek1543** [comment]
@blazeur Anko is not compatible with all 2.1 and later Android Studio versions.
