### ISSUE TITLE
Kotlin 1.1

### ISSUE THREAD

**Issue by lukaspili** [Kotlin/anko#300]
Hello,

It would be nice to have a branch for Kotlin 1.1-beta and be ready for incoming release.
Especially for the new ```@DslMarker``` annotation, that would greatly improve usage of Anko :)

**Comment by xavier-fernandez** [comment]
It would also be interesting to support co-routines natively :)

**Comment by yanex** [comment]
`master` branch migrated to Kotlin 1.1, supporting the `@DslMarker` annotation, so this issue may be closed as "fixed".
Issue relevant to the coroutines support: #327
