### ISSUE TITLE
anko-sqlite:0.9

### ISSUE THREAD

**Issue by markGilchristBookingBug** [Kotlin/anko#302]
Currently I am trying to retrieve date from my data base using the anko-sqlite library.

I am unable to get the dates out of the cursor as they are in the cursor as Strings
the below code

    val date     = columns["DATE_SCANNED"] as String 

passes fine but

      val time    = columns["DATE_SCANNED"] as Date

 or

     val time    = Date(columns["DATE_SCANNED"] as Long * 1000)

causes a crash,

Is this a bug?  or I am doing something wrong?

**Comment by tkshnwesper** [comment]
You need to explicitly convert it to a Date object. See [this](http://stackoverflow.com/a/4216767/2513269).
