### ISSUE TITLE
0.9.1 jars are not available in jcenter

### ISSUE THREAD

**Issue by matsu911** [Kotlin/anko#308]
Hi guys,

I tried to use ver 0.9.1, but failed with no jars in jcenter.
It seems like 0.9.1 was not deployed to jcenter.
https://jcenter.bintray.com/org/jetbrains/anko/anko-sdk15/

Did the repository move or you forget to deploy jars?

**Comment by alexeybrod** [comment]
Hi.
I don't know why it's not on jcenter yet, but you can add JetBrains repository to your gradle file. Version 0.9.1 can be found there.

```
...
allprojects {
    repositories {
        ...
        maven { url 'https://dl.bintray.com/jetbrains/anko' }
    }
}
...
```

**Comment by matsu911** [comment]
Hi alexeybrod,

Your suggestion works!
Thank you for your help.
