### ISSUE TITLE
dependency 0.9.1 can't be resolved

### ISSUE THREAD

**Issue by jeantuffier** [Kotlin/anko#309]
I'm trying to compile the anko-test project (https://github.com/yanex/anko-example.git) but gradle can't resolve the dependency to the library : 
```
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find org.jetbrains.anko:anko-sdk15:0.9.1.
     Required by:
         anko-example:app:unspecified
```

**Comment by sindrenm** [comment]
This is probably a duplicate of #308. :wink:

**Comment by dokinkon** [comment]
I can resolve the dependency by typing org.jetbrains.anko:anko-sdk15:**0.9**

**Comment by yperess** [comment]
Looking at jcenter they never pushed 0.9.1

https://jcenter.bintray.com/org/jetbrains/anko/anko-sdk23/

**Comment by yanex** [comment]
See also #313.

**Comment by sindrenm** [comment]
Nice, @yanex!
