### ISSUE TITLE
Anko Preview should support actual versions of Android Studio and IntelliJ IDEA

### ISSUE THREAD

**Issue by yanex** [Kotlin/anko#314]

**Comment by krokofant** [comment]
Does this mean something is happening around this issue?

**Comment by sindrenm** [comment]
Now that they've [landed on ConstraintLayout 1.0][1], perhaps they're also done changing up the internals of the Previewer? :tada: 

[1]: https://sites.google.com/a/android.com/tools/recent/constraintlayout10isnowavailable

**Comment by Prokky** [comment]
Any update?

**Comment by baoxin** [comment]
Any update?

**Comment by yole** [comment]
When we have an update, we'll update the issue.

**Comment by Miha-x64** [comment]
If this plugin is going to be reworked, what about previewing not only for AnkoComponent, but also for arbitrary expression, e. g. preview `createTheCoolestItemView()` function call output?

**Comment by yanex** [comment]
Anko DSL Preview plugin is rewritten in order to support Android Studio 2.4.
The updated plugin will be released with the upcoming Anko 0.10.

**Comment by yanex** [comment]
@Miha-x64 This would be quite difficult to implement. By the way, here's the feature request about supporting custom View classes: https://github.com/Kotlin/anko/issues/116.

**Comment by stepango** [comment]
@yanex Is there any way we could see the preview without rebuilding the project?

**Comment by Miha-x64** [comment]
...what about using scripting engine to run updated core on-the-fly?
