### ISSUE TITLE
pass resource identifiers to helper methods not work

### ISSUE THREAD

**Issue by wsw22** [Kotlin/anko#316]
[https://github.com/Kotlin/anko#using-resource-identifiers](url)

It is said " in Anko you can pass resource identifiers both to helper methods (button(R.string.login)) and to extension properties (button { textResource = R.string.login }). " 

When I try this, button(R.string.login) doesn't work. This is the code. am i missing something

`        verticalLayout {
            button(R.string.login)
            button { textResource = R.string.login }
        }`

**Comment by yanex** [comment]
The first parameter in the `button()` function is `theme`. Please change your code to `button(text = R.string.login)`.
It will be changed in Anko 0.10, though (the `button()` function that accepts the `theme` parameter will be renamed to `themedButton()`).

**Comment by yanex** [comment]
Fixed in a2f55e63431eec358d951f587e333e9359ce11d7.
