### ISSUE TITLE
Add Promises to Anko

### ISSUE THREAD

**Issue by yanex** [Kotlin/anko#319]

**Comment by adelnizamutdinov** [comment]
I use anko for layouts and absolutely love it, but there is so much more to anko than just layouts, and that adds to the method count

are there any plans to keep the anko lib small and lean?

**Comment by yanex** [comment]
@adelnizamutdinov Yes, of course. If any part of Anko will become significantly huge, it will be moved to the separate JAR.
By the way, 'kotlinx.coroutines' provide decent "promise" support so this issue may be closed.
