### ISSUE TITLE
Is it in plans to support reactive UI updates with Anko, similar to what Anvil does?

### ISSUE THREAD

**Issue by NeverwinterMoon** [Kotlin/anko#321]
Anvil has Anvil#render which allows to re-render the UI. It can be triggered manually and is triggered automatically in case of event listeners.

Is there something like this in plans? If no, what would be the most elegant way to do this when using Anko?

**Comment by Miha-x64** [comment]
It's quite easy to emulate such behaviour by defining your layout in a method and re-rendering (invoking) it when you need.

**Comment by cuddlecheek** [comment]
@NeverwinterMoon
I think you meant something called Data binding. I would like to see recommended way to make data binding too.

The closest thing I've found about it is: https://medium.com/lewisrhine/data-binding-in-anko-77cd11408cf9

**Comment by yanex** [comment]
It would be a completely new DSL with much more complicated wrappers. If even JetBrains will create the reactive Android UI framework someday, most likely it will have the different name.
