### ISSUE TITLE
Android Studio does not download sources of Anko 0.9.1a

### ISSUE THREAD

**Issue by mvysny** [Kotlin/anko#336]
Android Studio will then decompile the Kotlin sources, which does not contain any implementation, just /** compiled code */
Ideally, Android Studio should download the sources automatically. Yet, for some reason, the sources are not downloaded for Anko (all other libraries have sources). I can see that the sources are there: https://bintray.com/jetbrains/anko/anko/0.9.1a#files/org/jetbrains/anko/anko-sdk15/0.9.1a
So it seems that Android Studio is ignoring them? I know this is probably a bug in Android Studio, but could you guys give me a hint on how to download those sources?

**Comment by mvysny** [comment]
Interestingly, the sources for anko-sdk15 0.9 are present just fine in my Android Studio. I'm really at loss as to what's happening here.

**Comment by yanex** [comment]
That might be a bug in the Kotlin plugin (it ignores source jars for the Kotlin libraries).

Please try if you can navigate to sources for some other Kotlin library. If no, please file an issue to the Kotlin YouTrack: http://youtrack.jetbrains.com/

**Comment by mvysny** [comment]
It seems that Android Studio also fails to download sources for Koi-0.5.4; filed a bug against the Kotlin plugin: https://youtrack.jetbrains.com/issue/KT-17317
Thanks for help!
