### ISSUE TITLE
Right to left support

### ISSUE THREAD

**Issue by cuddlecheek** [Kotlin/anko#343]
How do I support RTL layouts?

1. consider this layout:

```
verticalLayout {	
    textView {
            text = "whatewer"
            textSize = ...
     }
}
```

1. set `android:supportsRtl="true"` in the manifest in application tag.

1. go to developer settings on the device and check "force RTL layout direction". The textview should be aligned on the right, but it's not and documentation doesn't mention anything about supporting RTL.

**Comment by piotrek1543** [comment]
@cuddlecheek check this post: http://yaronvazana.com/2015/10/29/adding-rtl-support-to-your-android-app-tutorial/

All you need to do is set `marginStart`, `marginEnd`, `paddingStart`, `paddingEnd` etc.

where:
`start` is a position `left` on the phones with RTL support enabled.
`end` is a position `right` on the phones with RTL support enabled.

**Comment by cuddlecheek** [comment]
@piotrek1543 This isn't what I meant. I know how start/end properties work. I was talking about the Android layout mirroring. It is mentioned in your post too:

> Android automatically mirrors your layout, just make sure you’re satisfied with the result. In case something went wrong, try to replace elements with other supported and newer once. I found the LinearLayout and the RelativeLayout to work perfectly.

However, I didn't realize that the layout mirroring in `LinearLayout` won't work when orientation vertical is set. Which means I'll close this issue anyway.
