### ISSUE TITLE
startActivityForResult

### ISSUE THREAD

**Issue by mikesol** [Kotlin/anko#346]
anko's `Intent` helpers are great! They'd be even greater if there were helpers for `startActivityForResult` which I use far more often than the vanilla `startActivity`.

I've written some extension functions to make this happen but it seems like `anko` proper would be a good place for them - it's just a few lines of code in `anko/library/static/common/src/Intents.kt`. Any chance this could make it into a future release candidate?

**Comment by piotrek1543** [comment]
@mikesol add new pull request with your changes, It might be useful

**Comment by yanex** [comment]
There are helpers for `startActivityForResult`. They support Activity or Fragment receivers:

https://github.com/Kotlin/anko/blob/master/anko/library/static/common/src/Intents.kt#L41
