### ISSUE TITLE
[SQLite] Support for UNIQUE conflict clauses

### ISSUE THREAD

**Issue by monxalo** [Kotlin/anko#353]
Support for table UNIQUE conflict clauses would be nice, e.g.:
```
CREATE TABLE table_name
(
  _id INTEGER PRIMARY KEY AUTOINCREMENT,
  record_id INTEGER NOT NULL,
  ...
  , UNIQUE ( record_id ) ON CONFLICT REPLACE
)
```
`ON CONFLICT` [clause](https://sqlite.org/lang_conflict.html):
* ROLLBACK
* ABORT
* FAIL
* IGNORE
* REPLACE

**Comment by jlandrum** [comment]
Isn't this already available?

[https://github.com/Kotlin/anko/blob/master/anko/library/static/sqlite/src/sqlTypes.kt](url)

**Comment by monxalo** [comment]
Yes, UNIQUE is already available. This is to support conflict clauses.

**Comment by monxalo** [comment]
A simpler version of the example can also be written like so:
```
CREATE TABLE table_name
(
  _id INTEGER PRIMARY KEY AUTOINCREMENT,
  record_id INTEGER NOT NULL UNIQUE ON CONFLICT REPLACE,
  ...
)
```
