### ISSUE TITLE
is any way to implement this?

### ISSUE THREAD

**Issue by pinkApple** [Kotlin/anko#358]
I want to know if we can using XML but in android studio compiling time,  auto transverse XML  to 'anko' code,
because Anko can be more efficient, I think there must be cool!
anyone have some information about this or some plugins?

**Comment by yanex** [comment]
I don't know about such plugins. Moreover, not all XML layouts may be converted to Anko DSL as is, and it would be the hard job to make a converter that will work in 100% cases.
