### ISSUE TITLE
Android Studio 2.4 Preview 7 not compatible with plugin

### ISSUE THREAD

**Issue by krokofant** [Kotlin/anko#368]
Following #314 I have downloaded the latest 2.4 preview but the latest plugin 0.9b from [here](https://plugins.jetbrains.com/plugin/7734-anko-dsl-preview) says it's not compatible.

Also noted from user otetc that Preview 6 doesn't work either (20.04.2017)

**Comment by yanex** [comment]
Please test `anko-ide-plugin.zip` from this: https://teamcity.jetbrains.com/viewLog.html?buildId=1067204&tab=artifacts&buildTypeId=ProjectsWrittenInKotlin_Anko
The bug was fixed in Anko 0.10.

**Comment by deviant-studio** [comment]
i've just tried new plugin and encountered with problems:
1. the preview window pops up on activities and other classes that has nothing to do with anko. it would be nice if preview works only on supported classes (AnkoComponent)
2. my ide hangs with no response when i'm trying to create AnkoComponent and copy-paste some layout snippet there.

**Comment by deviant-studio** [comment]
I was able to see layout preview of my `AnkoComponent`. Now when i'm trying to add constructor param the preview window fails to render content
```
Exception Details java.lang.NoSuchMethodError: ds.ankobindings.Component: method  ()V not found   at __anko.preview.View.init  at __anko.preview.View.<init>  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)   at android.view.LayoutInflater.inflate(LayoutInflater.java:495)   at android.view.LayoutInflater.inflate(LayoutInflater.java:397) Copy stack to clipboard   
```

**Comment by yanex** [comment]
@deviant-studio The preview is only available to `AnkoComponent` classes with the zero-parameter constructor. Add a default value to that parameter or add some another constructor.
The exception shown, though, is a bug. I will investigate this shortly.

**Comment by yanex** [comment]
@deviant-studio You mean that the preview pops up on unrelated classes even if it was hidden? Or you mean it is not hidden automatically?

**Comment by deviant-studio** [comment]
>  Add a default value to that parameter 
yep. already solved. thanks

> You mean that the preview pops up on unrelated classes even if it was hidden?
i mean hidden/visible state is mutual for all tabs, not per tab like it implemented in xml layouts. it is minor inconvenience though.

**Comment by yanex** [comment]
@deviant-studio Well, in case of the XML layout, the XML file being shown is a *complete* declaration. In case of DSL, any other files may potentially contain significant portions of the layout, so the preview tool window is not hidden automatically.
But if you still think it is a user-experience issue, please create a ticket with this. Maybe some preference may be added later.
