### ISSUE TITLE
CoordinatorLayout is missing

### ISSUE THREAD

**Issue by bvolkmer** [Kotlin/anko#380]
Hey,
The CoordinatorLayout has no extension function to ViewManager.

When I search the GitHub Repo I find this as generated, but it is not packed in the 0.10.0 jcenter jar (anko-sdk25-0.10.0-sources.jar).

Greetings,

**Comment by yanex** [comment]
`CoordinatorLayout` is a part of the `design` support library.
Please add `compile "org.jetbrains.anko:anko-design:$anko_version"` to your project dependencies (https://github.com/Kotlin/anko#gradle-based-project).

**Comment by bvolkmer** [comment]
Ah. Thanks. I missunderstood the README, as I thought the meta package includes the support libraries too.
