### ISSUE TITLE
Gradle build fails on AS 3.0 canary 1 w/Anko dependency

### ISSUE THREAD

**Issue by brezinajn** [Kotlin/anko#381]
When included ```compile "org.jetbrains.anko:anko:0.10.0"``` gradle build throws ```Error:Failed to resolve: com.google.android:android:2.3.1``` on Android Studio 3.0 Canary 1 w/gradle:3.0.0-alpha1.

**Comment by rocketsummer** [comment]
I'm seeing the same issue. How do I fix it?

**Comment by lusongcai** [comment]
Anko doesn't support AS 3.0 canary1?

**Comment by walfud** [comment]
I change buildscript deps to `classpath 'com.android.tools.build:gradle:2.4.0-alpha7'` solved the problem. but a warning: "Warning:Ignoring Android API artifact com.google.android:android:2.3.1 for debug"
It seems that newest 3.0 version treat it as error.

**Comment by sonnytron** [comment]
I guess we'll just have to wait for Anko to give an Alpha build that we can use

**Comment by m43bloe** [comment]
Obviously a hack for now, but I got this to build with `3.0.0-alpha1` by doing this:

```
compile("org.jetbrains.anko:anko:0.10.0") {
        exclude group: 'com.google.android', module: 'android'
    }
```

**Comment by andre-artus** [comment]
I get the same warning for Anko 0.10.0 in Android Studio 2.3.2 
Build #AI-162.3934792, built on April 21, 2017
JRE: 1.8.0_112-release-b06 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by evolify** [comment]
i get the same error

**Comment by yanex** [comment]
Relevant issue in Kotlin issue tracker: https://youtrack.jetbrains.com/issue/KT-18103

**Comment by mengming** [comment]
I have the same error too. Any solution now?

**Comment by qssq** [comment]
i not understand ,how to modify my code?
