### ISSUE TITLE
Cannot Load Project (Anko v0.10.0 | AS v2.3.2)

### ISSUE THREAD

**Issue by e16din** [Kotlin/anko#386]
StartupAbortedException
<img width="501" alt="2017-05-22 13 04 22" src="https://cloud.githubusercontent.com/assets/1799923/26303240/a74b9bd2-3eef-11e7-876a-f865df13596b.png">

**Comment by antoniovj1** [comment]
Same problem with AS v2.3.2

**Comment by yole** [comment]
The new DSL preview plugin is only compatible with Android Studio 3.0 Canary. Don't install it if you're using Android Studio 2.3.
