### ISSUE TITLE
How to use lparams

### ISSUE THREAD

**Issue by MadeRelevant** [Kotlin/anko#392]
Hi,

I am playing with anko for a few days and like it pretty much so far. Created some custom views which also went quite well.

The question I have is when to use lparams at which place? I understand that at top level elements you should do something like:

```java
verticalLayout {
    lparams(...) { ... }
}
```

But sometimes you should / can use:

```java
verticalLayout {
    editText {
        lparams(...) {...} // <---- seems to work sometimes as well
    }.lparams(...) {...} // <---- is this preferred / different from within editText{} ?
}
```

What is the difference between these two approaches? I can provide an example where it is actually working differently / not applying the lparams if required.

Thanks for the info already.

**Comment by yanex** [comment]
You should always write

```kotlin
verticalLayout {
    // code
}.lparams { ... }
```

The other ways may be bug-prone. For example, by writing this:

```kotlin
verticalLayout {
    lparams { ... }
}
```

you actually say "I want to put the newly created `verticalLayout` into another `LinearLayout`". If you put it to some other layout, you'll get a runtime exception.

**Comment by MadeRelevant** [comment]
Alright, thanks for the heads up.
