### ISSUE TITLE
DSL Preview error

### ISSUE THREAD

**Issue by ashish2810** [Kotlin/anko#398]
I'm encountering the following error:

The following classes could not be instantiated:
- __anko.preview.View (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.  If this is an unexpected error you can also try to build the project, then manually refresh the layout.  Exception Details java.lang.ClassNotFoundException: com.ashish.link.MyActivityUI   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)   at __anko.preview.View.init  at __anko.preview.View.<init>  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)   at android.view.LayoutInflater.inflate(LayoutInflater.java:495)   at android.view.LayoutInflater.inflate(LayoutInflater.java:397) Copy stack to clipboard

**Comment by yanex** [comment]
Can you please show the class that you want to preview (or at least its part)?
Is the error stable, or it goes away after the re-importing (or building) the project?

**Comment by ashish2810** [comment]
Error is stable.

The class is:

`class MyActivityUI : AnkoComponent<MyActivity>{
    override fun createView(ui: AnkoContext<MyActivity>)=ui.apply {
        verticalLayout{
                backgroundColor=R.color.material_blue_grey_800
                textView {
                    text="Hello World!"
                }
                button {
                    toast("Click Me")
                }
            }
    }.view
}`

**Comment by seaskyways** [comment]
I am having exact similar error.
The following classes could not be instantiated:
- android.support.v7.widget.AppCompatImageView (Open Class, Show Exception, Clear Cache)
- __anko.preview.View (Open Class, Show Exception, Clear Cache)
- android.support.v7.widget.AppCompatTextView (Open Class, Show Exception, Clear Cache)

**Comment by JoeMaher** [comment]
Im see the same issue, 

`class StartActivity: AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        StartLayout().setContentView(this)
    }
}`

`class StartLayout: AnkoComponent<StartActivity> {

    override fun createView(ui: AnkoContext<StartActivity>): View {
        return with(ui) {
            linearLayout {
                lparams(width = matchParent, height = matchParent)
                backgroundColor = ContextCompat.getColor(ctx, R.color.darkBlue)
            }
        }
    }
}`
