### ISSUE TITLE
View.onClick() extension method missing in Anko 0.10.1?

### ISSUE THREAD

**Issue by mvysny** [Kotlin/anko#412]
The `View.onClick()` extension method located in `Sdk15ListenersKt` class in Anko 0.9.1 is missing in Anko 0.10.1, and it has not been announced that it is going to be deleted. In fact, it's still announced in on the main Anko page: https://github.com/Kotlin/anko, so I guess it was not removed on purpose, but maybe rather moved to some other artifact?

**Comment by erickok** [comment]
From the releases page under 0.10 I find:
> DSL listeners moved to anko-<platformName>-listeners artifacts (e.g. anko-sdk25-listeners);
That helped me.

**Comment by arezaee** [comment]
hey
I don't understand what's that mean?

    DSL listeners moved to anko-< platformName >-listeners artifacts (e.g. anko-sdk25-listeners);

**Comment by CliffBrown** [comment]
@arezaee it means you should update your gradle file accordingly.

![image](https://user-images.githubusercontent.com/3011622/35297178-258d7cde-0076-11e8-84da-ac687fc0691a.png)

**Comment by arezaee** [comment]
@CliffBrown 
thank you so much
