### ISSUE TITLE
Anko: cannot set text of TextView with String

### ISSUE THREAD

**Issue by viktoria-shirunova** [Kotlin/anko#416]
```
        verticalLayout {
            val edit = editText {
                text = "aaa" // compile error: type mismatch: required Editable!  found String
                setText("aaa") // but setText works ok
            }
        }
```
At the same setting the same property without using Anko works:
```
        val edit = findViewById(R.id.text1) as TextView
        edit.text = "hello"
```
Similar text setting in button works ok too:
```
        verticalLayout {
            button {
                text = "aaa" // here compiles ok
            }
        }
```

**Comment by er-abhishek-luthra** [comment]
I faced the same issue myself while migrating my project to kotlin . I spend some time to find reason to why it was happening and later discovered that jetbrains have forgotten to specify it in the official documentation. I have written a detailed post to answer how kotlin property generation works for java getters and setters . Just follow the post below.

https://medium.com/@er.abhishek.luthra/how-does-kotlin-generated-property-from-java-getters-and-setters-undocumented-by-jetbrains-7e1ad88052b1
