### ISSUE TITLE
[Feature] Support android.support.v4.app.Fragment

### ISSUE THREAD

**Issue by XieEDeHeiShou** [Kotlin/anko#417]
I'm using anko-common, trying to make a toast in android.support.v4.app.Fragment like I usually do in Activity/Context...I get an error tip..

Then I read the source code Intents.kt and Toasts.kt, they only support android.app.Fragment.
![tim 20170622225510](https://user-images.githubusercontent.com/16363180/27440621-e2fc1e24-579d-11e7-95a1-aa40f7b15a85.png)
![tim 20170622225525](https://user-images.githubusercontent.com/16363180/27440622-e30b8e04-579d-11e7-9e6e-4813e917da33.png)

I known it's esay to write another extensions.kt..
Will anko support v4.app.Fragment ?

**Comment by albodelu** [comment]
Add the proper dependency:
   `implementation "org.jetbrains.anko:anko-support-v4-commons:0.10.1"`

Also add the correct import manually (...anko.* it's not enough)
   `import org.jetbrains.anko.support.v4.*`

SupportIntents.kt:
![screen shot 2017-08-11 at 08 54 48](https://user-images.githubusercontent.com/18224621/29203682-d0ba6f62-7e72-11e7-8aea-2a49aefcc28e.png)

SupportDialogs.kt:

![screen shot 2017-08-11 at 08 58 13](https://user-images.githubusercontent.com/18224621/29203740-3ee2291c-7e73-11e7-9a01-e154451e2e7d.png)
