### ISSUE TITLE
How to use SwipeRefreshLayout ? 

### ISSUE THREAD

**Issue by cjhandroid** [Kotlin/anko#420]

**Comment by cjhandroid** [comment]
I want to use RecyclerView in SwipeRefreshLayout? Is this Right?4
`swipeRefreshLayout {
                setColorSchemeColors(0xE94653)
                RecyclerView(ui.owner)
            }.lparams(matchParent, matchParent)`

**Comment by 4u7** [comment]
Take a look https://github.com/JetBrains/kotlinconf-app/blob/master/android/app/src/main/java/com/jetbrains/kotlinconf/ui/SessionListFragment.kt#L99
