### ISSUE TITLE
Using Anko for Rounded Corners (Shapes?)

### ISSUE THREAD

**Issue by nickyhajal** [Kotlin/anko#433]
Hi - I'm trying to make a button with rounded corners. Is there anyway to use Anko to streamline this process?

For example, can Anko be used to replace shape XML files as well?

Thanks!

**Comment by hasenj** [comment]
You can already do this with basic kotlin:

Define the shape (as a function):

    fun buttonBg() = GradientDrawable().apply {
        shape = GradientDrawable.RECTANGLE
        cornerRadius = 6f
        setStroke(2, grey)
        ....
    }

Use it on a button:

    button {
        ....
        background = buttonBg()
    }

Actually you can use it on anything, not just a button. In my project I use it on a linearLayout and it works just as well.

**Comment by nickyhajal** [comment]
Perfect, thanks so much!
