### ISSUE TITLE
Difference between text size of anko libs and textsize xml layout

### ISSUE THREAD

**Issue by jackyhieu1211** [Kotlin/anko#446]
I have use textSize of Anko
   textSize = sp(16).toFloat()
But. textSize very Big.
 textSize 16sp of xml Layout is smaller textSize of Anko

Difference between text size of anko libs and textsize xml layout ??

**Comment by arslancharyev31** [comment]
This is because `TextView`'s `setTextSize` already interprets value in scaled pixel units. Instead, you should be using just `16f`. This is equivalent to `16sp` in xml.

**Comment by arslancharyev31** [comment]
This is because `TextView`'s `setTextSize` already interprets value in scaled pixel units. Instead, you should be using just `16f`. This is equivalent to `16sp` in xml.

**Comment by jackyhieu1211** [comment]
thanks you.

**Comment by spkingr** [comment]
Solved my problem! Great!

**Comment by yohni** [comment]
thanks
