### ISSUE TITLE
if conditions and repeats: to add to the DSL ?

### ISSUE THREAD

**Issue by paul-hammant** [Kotlin/anko#502]
Swiby (JRuby and Swing), Shoes (Ruby and WxWindows) are two DSLs in the same style that had if conditions and for-loops.  I have them both here - https://paulhammant.com/ui-markup-nirvana/ - and other similar techs. 

In 2009 Angular gave HTML the same two things - if conditions and loops.

Anko would push to a new level with these two, too.

**Comment by 4u7** [comment]
What problem do you have using if conditions and loops with Anko? You can use any Kotlin feature with Anko.

**Comment by paul-hammant** [comment]
That's great news - can you show some examples of the DSL showing for loops and if conditions?

**Comment by paul-hammant** [comment]
The way the flutter team have their information architecture is really clear. Refer https://www.dartlang.org/samples#control-flow-statements for if conditional and for-loops. It's really easy for the casual reader to see the power of this stuff.

**Comment by 4u7** [comment]
We have pretty good docs about Kotlin https://kotlinlang.org/docs/reference/control-flow.html. You can use everything you find there with Anko. Anko DSL is just Kotlin code.

**Comment by paul-hammant** [comment]
You're in charge of your own OSS pieces, we'll agree to disagree :)
