### ISSUE TITLE
ALTER TABLE

### ISSUE THREAD

**Issue by kuleshovdv** [Kotlin/anko#525]
How I can modify existing tables? There is no ALTER TABLE request in Anko SQL API.

**Comment by ParkerK** [comment]
@kuleshovdv did you figure it out? I'm also curious as to how to do this.

**Comment by kuleshovdv** [comment]
@ParkerK Just use `execSQL` method
`db.execSQL("ALTER TABLE mytable RENAME TO oldtable;")` 
and other ALTER TABLE requests this way
