### ISSUE TITLE
kotlin-reflect Warning

### ISSUE THREAD

**Issue by Joslyn-Chen** [Kotlin/anko#534]
`Warning:Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    C://.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jre7/1.2.10/ea1aafdd031ba2604b06cb89a97da397b7aff520/kotlin-stdlib-jre7-1.2.10.jar (version 1.2)
    C://.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.1.1/e68cf130c2dbdd68a72f4a750cf442dffcd877ce/kotlin-reflect-1.1.1.jar (version 1.1)
    C://.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.2.10/b9bf650516989595a5390e5a54181e16347208ac/kotlin-stdlib-1.2.10.jar (version 1.2)`
How to lift the warning

**Comment by z3ndNadim** [comment]
https://kotlinlang.org/docs/reference/compatibility.html

**Comment by Joslyn-Chen** [comment]
@z3ndNadim thank you. 谢谢。

**Comment by z3ndNadim** [comment]
Welcome
