### ISSUE TITLE
Anko DSL preview can’t work(Anko version 0.10.4)

### ISSUE THREAD

**Issue by linuhap** [Kotlin/anko#540]
I have a error in Anko Layout Preview:
The following classes could not be found:
- __anko.preview.View (Change to android.media.tv.TvView, Fix Build Path, Edit XML, Create Class)

**Comment by rafayali** [comment]
Tried using 0.10.3? As 0.10.4 is having some weird problems. See #536

**Comment by 4u7** [comment]
Could you try this hotfix build? (Click "Login as guest")
https://teamcity.jetbrains.com/repository/download/ProjectsWrittenInKotlin_Anko/1288995:id/anko-ide-plugin.zip
