### ISSUE TITLE
Cannot edit source code

### ISSUE THREAD

**Issue by bhbfhfb** [Kotlin/anko#541]
![save](https://user-images.githubusercontent.com/2010785/34552083-b666c364-f162-11e7-815e-427264cc7148.png)

I don't know what is it.
Cannot edit source code when using 'Anko Support' However, if disabled, it will work.

Anko version : 0.10.4

**Comment by 4u7** [comment]
Could you try this hotfix build? (Click "Login as guest")
https://teamcity.jetbrains.com/repository/download/ProjectsWrittenInKotlin_Anko/1288995:id/anko-ide-plugin.zip

**Comment by bhbfhfb** [comment]
Thank you.
This problem does not occur.
