### ISSUE TITLE
android studio 3.0.1 not show anko layout preview

### ISSUE THREAD

**Issue by evansherry** [Kotlin/anko#551]
```
kotlin_version:1.2.10
anko_version: 0.10.4

gradle version: 3.0.1
```
Running on the phone can be displayed, but the preview can not be displayed, this is a bug！

![image](https://user-images.githubusercontent.com/11881751/35074645-d364d916-fc29-11e7-9d0b-8e62fe2b2c9a.png)

**Comment by evansherry** [comment]
@sd5869  I'm sorry, you are right , thx

**Comment by dawit-abraham** [comment]
@evansherry would you please provide a link to your working project repo. I am stack for 3 days with the same problem, and tried almost everything

**Comment by GraxMonzo** [comment]
You need build your project everytime when you need preview
