### ISSUE TITLE
Exception handling with async { }

### ISSUE THREAD

**Issue by MariusBoepple** [Kotlin/anko#559]
Hi guys, I'm quite new to Kotlin coroutines + Anko and so far quite impressed by your work!

Now here's the problem. We're fetching data on a background thread with `bg { }`. At some point during development, the `showData()` method wasn't called anymore and we wondered what's the problem until we debugged and discovered that `getData()` threw a `JSONParseException`. So that's just one real-life use-case of that 😄 

```kotlin
async(UI) {
    val data: Deferred<Data> = bg {
	getData() // this method will throw an Exception
    }

    // This will never be called? 
    showData(data.await())
}
```

At this point, it would have been much easier for us if there had been an exception. Also, I'm wondering if this is really what we want in production - for us, it would be better to see the problems directly (e.g. in Crashlytics).

I've also made some research and there were some issues half a year ago about this topic without a real solution (#182, #271).

So I'm asking here again (sorry): Is there a **"default" way how to see/throw exceptions inside of `async(UI){ }`?** Adding a few lines of code manually to every call isn't a real solution in my eyes since developers will forget it and user will report things we aren't aware of... Besides, what's the advantage of hiding them anyway?

**Comment by AllanWang** [comment]
Isn't `async` deprecated in Anko?

I think you should be using `doAsync` instead. Likewise, exceptions are consumed by default, but you can add your own consumer to log it in crashlytics.

To me at least, consuming exceptions is beneficial, as a lot of uses for async involves fetching something that may or may not help enhance the UI. In many cases, I'd rather have it fail silently and not crash the entire app if something changes.

Naturally, if you want to avoid all this, you can simply supply your own try catch as well and handle everything before it makes it to the base consumer. You can also set your consumer to only throw the exceptions when debugging

**Comment by MariusBoepple** [comment]
Ah sorry - We're using `async()` from `kotlinx.coroutines` - so that's not deprecated, right? Our solution now is the following: 

```
fun <T> asyncx(
        context: CoroutineContext,
        start: CoroutineStart = CoroutineStart.DEFAULT,
        block: suspend CoroutineScope.() -> T
) : DisposableHandle {
    return  kotlinx.coroutines.experimental.async(context, start, block).invokeOnCompletion { e -> e?.let{
        e.printStackTrace()
        throw e
    } }
}
```
Discussed here: https://github.com/Kotlin/kotlinx.coroutines/issues/100

I think the wiki should be updated and pointed out clearly that `async()` was moved to `kotlinx.coroutines`

**Comment by AllanWang** [comment]
As your referenced issue suggests, you may try propagating errors on `launch`. Maybe you'll also want to move this issue, as this no longer applies to Anko.

**Comment by MariusBoepple** [comment]
But we want to use the `async()` functionalities with `Deferred.await()` to do multiple things concurrently (which is suggested in the wiki).

As far as I understand, Anko should be an abstraction layer for Android on top of the Kotlin coroutines -  so why shouldn't they provide an implementation of `async { }` which throws exceptions (at least after completion)?

**Comment by AllanWang** [comment]
It looks like the constructor is the same for both, so have you tried passing in your own context that overrides the exception handler? ([Link to post](https://github.com/Kotlin/kotlinx.coroutines/issues/100#issuecomment-320920786)).
