### ISSUE TITLE
Unable to use intentFor through startActivity

### ISSUE THREAD

**Issue by erniealice** [Kotlin/anko#571]
I've recently upgraded to Android Studio Canary 3.2 Build 3, this forces me to use Gradle 3.2.0 Alpha3

`dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0-alpha3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:3.1.1'
}` in the build.gradle file at the project level

There are no compilation errors, but when the following function is executed (say, clicking a button):
`fun goToNextActivity() { startActivity(intentFor<NextActivity>()) }`

I get the following error:
`java.lang.VerifyError: Verifier rejected class org.jetbrains.anko.internals.AnkoInternals: void org.jetbrains.anko.internals.AnkoInternals.fillIntentArguments(android.content.Intent, kotlin.Pair[]) failed to verify: void org.jetbrains.anko.internals.AnkoInternals.fillIntentArguments(android.content.Intent, kotlin.Pair[]): [0xB] 'this' argument 'Reference: java.lang.Object' not instance of 'Precise Reference: kotlin.Pair' (declaration of 'org.jetbrains.anko.internals.AnkoInternals' appears in /data/app/com.companyname.appname-zOXU28CMcn1uluhWSDOvag==/split_lib_dependencies_apk.apk:classes2.dex)`

The only way I can use `intentFor` right now is using Android Canary 3.2 Build 2 with `classpath 'com.android.tools.build:gradle:3.2.0-alpha3'`. Build 3 doesn't allow me to use `classpath 'com.android.tools.build:gradle:3.2.0-alpha2'` because it's unsupported, and it gives a compilation error.

**Comment by veresvit** [comment]
Hi, Anko dialogs don't work either on the same Android Studio configuration as @erniealice described.

**Comment by DakotaWhipple** [comment]
I'm on build 3 but used 'com.android.tools.build:gradle:3.2.0-alpha04' and it fixed this for me.
3.2 Canary 3 on Arch Linux

**Comment by erniealice** [comment]
Thank out @DakotaWhipple .. I'm using AS Canary 3.2 Build 4 and Gradle Alpha 4. Works fine now. Thanks!
