### ISSUE TITLE
Guideline cannot work in constraintlayout

### ISSUE THREAD

**Issue by spkingr** [Kotlin/anko#579]
While I use `guideline` in ConstraintLayout, it doesn't work at all, the code below cannot set the `orientation` (Why there is no such property?) of `guideline`, which is useless:

```
guideline {
                //here, cannot set the orientation of guideline
}.lparams(width = wrapContent, height = wrapContent)
```

Even though the code below can set the right orientation, but it does not work either:

```
constraintSet {
                create(ID_GUIDELINE, VERTICAL_GUIDELINE)
}
```

So, how to use GuideLines in ConstraintLayout properly?

Another question: I use ConstraintLayout(name it A) in Activity, and ConstraintLayout(B) in Fragment, then add or replace the B into/with A, the width is always inccorect (But if there is a RecyclerView in B, and set the `layoutParams` of B: 
`layoutParams = ViewGroup.LayoutParams(MATCH_PARENT, MATCH_PARENT)`, 
then it works correctly, but with only other widgets. like buttons/textviews/imageviews, it shows that B is very narrow.) So why?  and thanks to advanced for the reply!

**Comment by pandasys** [comment]
Maybe try something like:
```
        guideline {
          id = ID_GUIDELINE
        }.lparams(0, 0) {
          orientation = ConstraintLayout.LayoutParams.VERTICAL
          guideBegin = dip(80)
        }
```

**Comment by spkingr** [comment]
@pandasys Thank you very much! I tried and the code compiles successfully, but when the other views connect to the guideline, the constraint layout will display incorrectly, in my recyclerview the item use anko constraintlayout with guideline displays nothing:

applyConstraintSet {
        connect(
                START of ID_IMAGE_VIEW to START of PARENT_ID margin dip(10),
                END of ID_IMAGE_VIEW to START of ID_GUIDELINE margin dip(10)
        )

**Comment by spkingr** [comment]
@pandasys Thanks again, I have solved this problem, just set the `LayoutParams` in the item view of RecyclerView:

```
constraintLayout {
            layoutParams = ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT)
            //................
}
```

**Comment by pandasys** [comment]
Sorry for late reply. Glad you fixed it. Here's a snippet of one of my ViewHolder views (no guideline in this,but you get the idea)
```
root = constraintLayout {
        id = ID_LAYOUT
        layoutParams = ConstraintLayout.LayoutParams(MATCH_PARENT, dip(60))

        selectedImage = imageView {
          id = ID_IMAGE_VIEW
          image = verifiedDrawable
        }.lparams(imageSize, imageSize) {
          bottomMargin = imageMargin
          marginStart = startOrEnd
          topMargin = imageMargin
          bottomToBottom = PARENT_ID
          startToStart = PARENT_ID
          topToTop = PARENT_ID
        }

        titleView = textView {
          id = ID_TITLE_VIEW
          textAppearance = R.style.ApTextAppearance_Primary
          maxLines = 1
          singleLine = true
          ellipsize = TextUtils.TruncateAt.END
        }.lparams(0, wrapContent) {
          marginEnd = startOrEnd
          marginStart = between
          bottomToTop = ID_ERROR_VIEW
          endToEnd = PARENT_ID
          horizontalBias = 0.5F
          startToEnd = ID_IMAGE_VIEW
          topToTop = PARENT_ID
        }

```
