### ISSUE TITLE
Remove ProgressDialog as it's now deprecated

### ISSUE THREAD

**Issue by AkshayChordiya** [Kotlin/anko#591]
Let's remove `ProgressDialog` code from Anko as it's now deprecated

Anko Wiki for Progress Dialog: https://github.com/Kotlin/anko/wiki/Anko-Commons-%E2%80%93-Dialogs#progress-dialogs

ProgressDialog: https://developer.android.com/reference/android/app/ProgressDialog.html

**Comment by rosariopfernandes** [comment]
I think removing it might be a harsh decision. I like @SUPERCILEX 's suggestion to mark it as deprecated.
