### ISSUE TITLE
I wanna know what's the difference between anko.async and anko.doAsync?

### ISSUE THREAD

**Issue by mikite** [Kotlin/anko#607]
When I do  import anko.async, AS show error. while import anko.doAsync looks fine, with anko version 0.10.4. 
what's the difference between anko.async and anko.doAsync?

**Comment by 4u7** [comment]
There is no async in anko, it is part of coroutines library and used to create new coroutine. `doAsync` is part of anko-commons and is used to execute task on background thread.

**Comment by sindrenm** [comment]
IIRC, `doAsync` was called `async` previously. It was renamed as to not conflict with the _kotlinx.coroutines_ function by the same name.
