### ISSUE TITLE
SQL(query) error or missing database with AUTOINCREMENT

### ISSUE THREAD

**Issue by SeppPenner** [Kotlin/anko#608]
Hi, when I use anko-sqlite in Kotlin and add the DatabaseHelper class as below (Dependecies in Gradle are in, too):

```kotlin
package exampleproject.helper

import android.content.Context
import android.database.sqlite.SQLiteDatabase
import org.jetbrains.anko.db.*

class DatabaseHelper(ctx: Context) : ManagedSQLiteOpenHelper(ctx, "FuelData", null, 1) {
    companion object {
        private var instance: DatabaseHelper? = null

        @Synchronized
        fun getInstance(ctx: Context): DatabaseHelper {
            if (instance == null) {
                instance = DatabaseHelper(ctx.getApplicationContext())
            }
            return instance!!
        }
    }

    override fun onCreate(db: SQLiteDatabase) {
        db.createTable("FuelData", false,
                "id" to INTEGER + PRIMARY_KEY + UNIQUE + AUTOINCREMENT,
                "fueled" to REAL,
                "kilometers" to REAL,
                "mileage" to REAL,
                "consumption" to REAL,
                "currentDate" to TEXT)
    }

    override fun onUpgrade(db: SQLiteDatabase, oldVersion: Int, newVersion: Int) {
        db.dropTable("FuelData", true)
    }
}

val Context.database: DatabaseHelper
    get() = DatabaseHelper.getInstance(getApplicationContext())
```

the app launches correctly but every time I try to use the database I get the following error:

> 
> 04-22 19:35:47.942 21148-21148/example.exampleproject E/SQLiteLog: (1) near "AUTOINCREMENT": syntax error
> [ 04-22 19:35:47.942 21148:21148 E/android.database.sqlite.SQLiteException: near "AUTOINCREMENT": syntax error (code 1): , whil android.database.sqlite.SQLiteException: near "AUTOINCREMENT": syntax error (code 1): , while compiling: CREATE TABLE  `FuelData`(id INTEGER PRIMARY KEY UNIQUE AUTOINCREMENT, fueled REAL, kilometers REAL, mileage REAL, consumption REAL, currentDate TEXT);
> #################################################################
> Error Code : 1 (SQLITE_ERROR)
> Caused By : SQL(query) error or missing database.
> (near "AUTOINCREMENT": syntax error (code 1): , while compiling: CREATE TABLE  `FuelData`(id INTEGER PRIMARY KEY UNIQUE AUTOINCREMENT, fueled REAL, kilometers REAL, mileage REAL, consumption REAL, currentDate TEXT);)
> #################################################################

Is there something I've missed to setup the database correctly or where is this error coming from?

**Comment by 4u7** [comment]
Try to use `AUTOINCREMENT ` without `UNIQUE`, i think they are mutually exclusive

**Comment by SeppPenner** [comment]
Hi @4u7. That's what I found out today in the morning, too.

> If a column has the type INTEGER PRIMARY KEY AUTOINCREMENT then a slightly different ROWID selection algorithm is used. 

See https://www.sqlite.org/autoinc.html.

And it works this way:

```kotlin
override fun onCreate(db: SQLiteDatabase) {
        db.createTable("FuelData", false,
                "id" to INTEGER + PRIMARY_KEY + AUTOINCREMENT,
                "fueled" to REAL,
                "kilometers" to REAL,
                "mileage" to REAL,
                "consumption" to REAL,
                "currentDate" to TEXT)
    }
```
