### ISSUE TITLE
Deprecate and remove methods that exist in Android KTX?

### ISSUE THREAD

**Issue by SUPERCILEX** [Kotlin/anko#614]
I'm proposing we deprecate and then remove all symbols that are duplicated by the [official Android KTX library](https://github.com/android/android-ktx). That would simplify code completion when using both libraries and ensure the community doesn't split. What do you think?

**Comment by touseefbsb** [comment]
this is surely a must do I think, will increase productivity of both libraries, as both libraries are great and must be simple to use together, and re implementing same thing with two libraries doesnt make any sense :)

**Comment by 4u7** [comment]
Yes, most of `anko-commons` will be deprecated at some point in favor of Android KTX. Probably closer to Android KTX release. If you wish to mark something already present in Android KTX with `@Deprecated` feel free to send pull request.

**Comment by SUPERCILEX** [comment]
@4u7 Sweet, see #617. I'd also love it if you could take a look at #616 since I rebased #617 out of it.
