### ISSUE TITLE
 Installing the anko library in Android 3.1.3

### ISSUE THREAD

**Issue by yvancoyaud** [Kotlin/anko#652]
Hello,
I'm trying to install the Anko library in Android 3.1.3 and I have the following error:
```
Failed to resolve: org.jetbrains.anko:anko:0.10.5-2
Open File
Show in Project Structure dialog
```
In the android configuration, I chose '**install JetBrains plugins**' and install '**Anko Support**'
This installation went well and gave me the version number 0.10.5-2

In the file 'build.gradle (Project: MyProject) I added: **ext.anko_version = '0.10.5-2'**
In the file 'build.gradle (Module: app) I added **implementation "org.jetbrains.anko: anko: $ anko_version"**

Please, can someone tell what I have forgotten, or what is the cause of this error.
Thank you for your answer to my question
Yvan COYAUD

**Comment by 4u7** [comment]
You should use 0.10.5 version number, `-2` suffix is plugin hotfix

**Comment by yvancoyaud** [comment]
Thank you for your prompt response.

Now all is OK
With the version number 0.10.5  the error has disappeared and I can do the 'import' of anko in my class

Merci
Yvan COYAUD
