### ISSUE TITLE
shouldn't snackbar DSL helpers take CharSequence?

### ISSUE THREAD

**Issue by pasniak** [Kotlin/anko#654]
android.support.design.widget API has
```
class Snackbar 
...
    /**
     * Update the text in this {@link Snackbar}.
     *
     * @param message The new text for this {@link BaseTransientBottomBar}.
     */
    @NonNull
    public Snackbar setText(@NonNull CharSequence message) {
```

https://github.com/Kotlin/anko/blob/4671683423e166a87e08de9f0645e5aed9d3887f/anko/library/static/design/src/main/java/Snackbar.kt#L61

**Comment by 4u7** [comment]
I think it should, feel free to send pull request
