### ISSUE TITLE
Blank view - Anko verticalLayout

### ISSUE THREAD

**Issue by douglasalipio** [Kotlin/anko#662]
Hi guys,

I'm trying to change the visibility of my component at runtime. It might be easy but after I change visibility = GONE my whole view became blank.

I just do something like that: 
       
```
      //creating my view
      childrenViews[position].createView(AnkoContext.create(UmbrellaApplication.instance, controller, false))
        tourHolderViewList.add(TourUI("#FF9ABE2E", umbrella190, text1, VISIBLE, GONE))
        tourHolderViewList.add(TourUI("#FF9ABE2E", walktrough2,text2, VISIBLE, GONE))
        tourHolderViewList.add(TourUI("#FFB83657", walktrough3, text3, VISIBLE, GONE))
```
   
```
 override fun createView(ui: AnkoContext<BaseController>) = ui.apply {
        verticalLayout {
            background = ColorDrawable(Color.parseColor(color))
            padding = dip(20)
            val caseImage = imageView(imageSource).lparams(width = dip(166), height = dip(166)) {
                gravity = Gravity.CENTER
                topMargin = dip(100)
                visibility = visibilityImage
            }
            val title = textView {
                textResource = textTourSource
                textSize = 24f
                textColor = Color.WHITE
                gravity = Gravity.CENTER
                visibility = visibilityImage
            }.lparams { gravity = Gravity.CENTER }

            val webTerms = webView {
                loadUrl("file:///android_asset/terms.html")
                visibility = visibilityWebView
            }.lparams(width = matchParent, height = dip(250))
        }
    }.view
```

**Comment by douglasalipio** [comment]
I fix that just creating another verticallayout which contains the webView.
 verticalLayout {
                 visibility = visibilityImage
                 val webTerms = webView { loadUrl("file:///android_asset/terms.html")
                 visibility = visibilityWebView
            }.lparams(width = matchParent, height = dip(250))
 }

**Comment by BejanAlina** [comment]
@douglasalipio instead of creating a new layout which might affect performance, you could simply call the visibility outside the creation block 

 val webTerms = webView {
                loadUrl("file:///android_asset/terms.html")
            }.lparams(width = matchParent, height = dip(250))

webTerms.visibilty = [...]

if anyone from contributors {@yanex} could tell us why, inside the block, the visibility modifier behaves strangely in this case

**Comment by douglasalipio** [comment]
@BejanAlina make sense. I'm gonna change for that. Thanks
