### ISSUE TITLE
Typo in dimensionRatio method name

### ISSUE THREAD

**Issue by wschurman** [Kotlin/anko#671]
The method [`ViewConstraintBuilder::dimensionRation`](https://github.com/Kotlin/anko/blob/27fba1aa00811470f58ec6b61851e1cd8c2d9999/anko/library/static/constraint-layout/src/main/java/ConstraintLayout.kt#L75) should be `dimensionRatio`.

Submitting a PR to fix this shortly.

**Comment by iceboundrock** [comment]
Hi @wschurman , your PR has been merged, could you please close this issue?
