### ISSUE TITLE
Anko Coroutines can not use in 1.2.71

### ISSUE THREAD

**Issue by lhl-012** [Kotlin/anko#676]
async(UI){}   UI can not import

**Comment by iFr0z** [comment]
because `async(UI){}` **deprecated**

**Comment by AlyssonPHN** [comment]
What's the alternative?

**Comment by iFr0z** [comment]
@AlyssonPHN [clear coroutines](https://github.com/Kotlin/kotlinx.coroutines/blob/master/ui/coroutines-guide-ui.md) without Anko wrapping.

> Example:
> ```
> abstract class ScopedAppActivity: AppCompatActivity(), CoroutineScope {
>     protected lateinit var job: Job
>     override val coroutineContext: CoroutineContext 
>         get() = job + Dispatchers.Main
>     
>     override fun onCreate(savedInstanceState: Bundle?) {
>         super.onCreate(savedInstanceState)
>         job = Job()
>     }
>         
>     override fun onDestroy() {
>         super.onDestroy()
>         job.cancel()
>     } 
> }
> ```
> 
> ```
> class MainActivity : ScopedAppActivity() {
> 
>     fun asyncShowData() = launch { // Is invoked in UI context with Activity's job as a parent
>         // actual implementation
>     }
>     
>     suspend fun showIOData() {
>         val deferred = async(Dispatchers.IO) {
>             // impl      
>         }
>         withContext(Dispatchers.Main) {
>           val data = deferred.await()
>           // Show data in UI
>         }
>     }
> }
> ```

**Comment by AlyssonPHN** [comment]
Oh, Thanks.
