### ISSUE TITLE
Why can't layoutParams be called inside of init functions?

### ISSUE THREAD

**Issue by schwiz** [Kotlin/anko#68]
`frameLayout{ layoutParams(matchParent, matchParent)}`
 vs the recommended 
`frameLayout{ }.layoutParams(matchParent, matchParent)`

I see doing it the first way only works partially, some attributes do not work like margins.  I think the required way really hurts the readability of the layout it would be preferable to put it inline.

**Comment by yanex** [comment]
http://blog.jetbrains.com/kotlin/2015/04/announcing-anko-for-android/#comment-33273

**Comment by schwiz** [comment]
Yeah I'm having a really hard time understanding how this works. I am having lots of issues with getting layoutParams to even compile a lot of the time it tries to goto the` val View.layoutProperties` helper instead. At runtime I get exceptions because my dsl is trying to add the incorrect layout params to the view.

**Comment by yanex** [comment]
I don't understand a problem mentioning `View.layoutProperties `. Could you provide an example?

**Comment by schwiz** [comment]
Sure inside a support Fragment the following won't compile because layoutParams for swipeRefreshLayout is scoping to `public var android.view.View.layoutParams: android.view.ViewGroup.LayoutParams?` inside of Properties.kt

```
        UI {
            swipeRefreshLayout = swipeRefreshLayout{
                setColorSchemeResources(R.color.primary, R.color.primary_light, R.color.accent, R.color.primary_dark)
                setOnRefreshListener(this@RecyclerFragment)
                recyclerView = customView {
                    layoutParams = RecyclerView.LayoutParams(matchParent, matchParent)

                }
            }.layoutParams(matchParent, matchParent)

        }
```

**Comment by yanex** [comment]
Setting a `RecyclerView.LayoutParams` to the view that is inside a `SwipeRefreshLayout` container is what you want to do?

**Comment by schwiz** [comment]
I just simply want both views to match parent rather than wrap content. If I had margins and stuff to set it would be a big problem but for now I just put the layoutParams call inside of the swipeRefreshLayout instead, like I'm doing for the recyclerView.  The recyclerView also has the same problem and I can not call layoutParams in the suggested way.

**Comment by yanex** [comment]
The problem should be fixed with the `DslMarker` annotation support from Kotlin 1.1 (#300).
Starting from Anko 0.10, you simply can't apply the wrong `lparams` since no candidates other than the direct parent ones are available.
If you have some another problem with the recommended syntax, please feel free to file the new issue.
