### ISSUE TITLE
Extension functions for Android classes

### ISSUE THREAD

**Issue by casadogg** [Kotlin/anko#688]
Hey, are extension functions for views, drawables, and classes belonging to Android welcome?

There's a few things I would like to see, such as:

• Change a drawable property such as color and size
• Functions for working with TextViews (ime actions ex functions, doOnX functions)
• Set compound drawables more easily
• And so on...

I feel like these functions could be part of the commons module. I'd like to contribute if you guys feel like this belongs in Anko.

**Comment by iceboundrock** [comment]
I am not an `Anko` team member. IMHO the [Android KTX](https://developer.android.com/kotlin/ktx) might be a better place for these extension functions.
