### ISSUE TITLE
Runtime error: HandlerContextKt not found in 0.10.7-rc13

### ISSUE THREAD

**Issue by eitzend** [Kotlin/anko#694]
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/android/HandlerContextKt;
        at org.jetbrains.anko.sdk27.coroutines.Sdk27CoroutinesListenersWithCoroutinesKt.onClick$default(ListenersWithCoroutines.kt:293)

This is with:
    ext.kotlin_version = '1.3.0'
    ext.anko_version = '0.10.7-rc13'

The call to onClick looks like this:
    relativeLayout { floatingActionButton { onClick {} } }

**Comment by jeiea** [comment]
It may be related with kotlinx-coroutines-android dependency. `Dispatchers.UI` was removed.

**Comment by eitzend** [comment]
I got it going. I had some references to org.jetbrains.kotlinx:kotlinx-coroutines-android:0.30.2 that needed to be org.jetbrains.kotlinx:kotlinx-coroutines-android:0.30.2-eap13.

My apologies.

**Comment by jeiea** [comment]
Why apologies? Isn't it anko's fault?
I can't make a project buildable with the current version of anko and coroutines-0.30.2-eap13. Could you let me know the correct gradle configuration?

**Comment by eitzend** [comment]
Ya ... Mine is working. I'll send you my config tomorrow, but look at all
your build.Gradle files to make sure it isn't calling out any issues. I had
some red underlines that weren't made obvious during the build.
