### ISSUE TITLE
version of intent declaration not found in the library

### ISSUE THREAD

**Issue by alfawzaan** [Kotlin/anko#697]
startActivity<TargetActivity>() is not available in the library. that is after adding the dependencies. but startActivity(intentFor<TartgetActivity>()) works.

**Comment by iceboundrock** [comment]
Please make sure you imported the `org.jetbrains.anko` package.

**Comment by alfawzaan** [comment]
Yeah thanks I discovered I was using anko and not anko-common

**Comment by iceboundrock** [comment]
I am glad that you resolved the problem, would you mind closing this issue? Thanks.

**Comment by alfawzaan** [comment]
Okay will do just that
