### ISSUE TITLE
How to run the project ?

### ISSUE THREAD

**Issue by ittianyu** [Kotlin/anko#709]
This is a great project. And I'm interested in `idea-plugin/preview`.
I used `IntelliJ IDEA 2018` to open the project. And it build success. 
But I don't know how to run the `preview` module and debug in `Android Studio`.
Can you help me ?

**Comment by iceboundrock** [comment]
You may want to read [this page](https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/running_and_debugging_a_plugin.html) first.

**Comment by 4u7** [comment]
@ittianyu I've pushed `Android Studio` run configuration
c338731784926bb4f6961f550c7626cc26e15460
