### ISSUE TITLE
Anko Commons stopped work after migration to AndroidX

### ISSUE THREAD

**Issue by KennedySDias** [Kotlin/anko#717]
I migrated my app to AndroidX and after this some functions stopped work, they has working before do.
All these errors just happening inside Fragment context, others use cases with Activity context are working.

These are:
startActivity<Class>() : 
Error message: "No type arguments expected for fun startActivity(p0: Intent!): Unit"

startActivityForResult<Class>()
Error message: "None of the following functions can be called with the arguments supplied:"

browse()
Error message: "Unresolved reference: browse"

toast()
Error message: " Unresolved reference: toast"

My current version: 0.10.8

**Comment by mustafahmalik** [comment]
in fragment you can call activity?.toast("message")

**Comment by KennedySDias** [comment]
The problem is no longer happening, but I do not know why.
