### ISSUE TITLE
About the layout performance

### ISSUE THREAD

**Issue by GainLee** [Kotlin/anko#742]
I compared the cold launch time between xml and anko on Huawei Mate10 Pro, by put 15 ImageViews to RelativeLayout and ConstraintLayout. Below is code file

[activity_main_constraint.xml.txt](https://github.com/Kotlin/anko/files/3112924/activity_main_constraint.xml.txt)
[activity_main_relative.xml.txt](https://github.com/Kotlin/anko/files/3112926/activity_main_relative.xml.txt)
[ConstraUI.kt.txt](https://github.com/Kotlin/anko/files/3112932/ConstraUI.kt.txt)
[RelativeUI.kt.txt](https://github.com/Kotlin/anko/files/3112933/RelativeUI.kt.txt)

and I got result
![image](https://user-images.githubusercontent.com/2909095/56671424-312caa00-66e7-11e9-9ac3-bda670cfbc70.png)

anko has no obvious advantage on performance, is there something wrong?

**Comment by ageevvalentin** [comment]
It`s working only for low-end devices and large amount of views. Also anko allows to do more flexible view building, for example, with using abstractions and reuse..

**Comment by GainLee** [comment]
> It`s working only for low-end devices and large amount of views. Also Anko allows to build views more flexible, for example, with using abstractions and reuse.

Hi guy, thanks for explanation。
