### ISSUE TITLE
Where is roadmap???

### ISSUE THREAD

**Issue by Sandmonster** [Kotlin/anko#746]
Anko is interesting library, I'm looking forward to using it to my projects, however version number says it's still very experimental. I think there are many people who also like me are interested in this project, so I think it would be useful to add a roadmap and some kind of versioning policy for this project to determine minimal functional for a stable release and how soon would be possible to use it

**Comment by ageevvalentin** [comment]
Google announced the release of the library for building UI. 
https://developer.android.com/jetpack/compose

**Comment by vladimirfx** [comment]
Does it means that project is discontinued? 
What is actual alternative to anko?

**Comment by Makentoshe** [comment]
There is a [post on Habr](https://habr.com/en/post/442440/) about AnkoLayouts and a part of AnkoCoroutines (Attention! Russian language)
Sorry about this impudent advertisement

**Comment by vladimirfx** [comment]
Can maintainers clarify project status?
We are on architecture planing for new project. Anko has very strong design for me. But project looks like discontinued. Can we consider Anko as base technology for out views?

**Comment by Makentoshe** [comment]
As i know, Anko is a JetBrains side project. All maintainers are busy by their main projects.

**Comment by Rasalexman** [comment]
anko is a great project, I don't really think that it will be closed in the future

**Comment by vkotovv** [comment]
This library is now deprecated, see https://github.com/Kotlin/anko/blob/master/GOODBYE.md
