### ISSUE TITLE
startActivityForResult called on wrong object (for Fragments)

### ISSUE THREAD

**Issue by porokoro** [Kotlin/anko#76]
The extension methods **```startActivity```** and **```startActivityForResult```** are always called on the ```Context``` object. For fragments these methods are called directly on the activity but fragments have their own implementation of these methods.

The Problem with this behavior is that the fragments callback **```onActivityResult```** never gets called when **```startActivityForResult```** is invoked directly on the context instead of on the fragment.

**Comment by guuilp** [comment]
This is happening to me on Anko 0.10.4 and Kotlin 1.2.10. @yanex may you help me?
