### ISSUE TITLE
about Anko performance

### ISSUE THREAD

**Issue by staney7** [Kotlin/anko#763]
I used Anko rebuild a complex view in our project and publish it in a beta . We collect 20000+ user's performance data . 

![image](https://user-images.githubusercontent.com/14358173/67540224-352d9900-f717-11e9-9b9b-1011ad920bb3.png)

why ?  Is there any problem about my UI?
[ui.txt](https://github.com/Kotlin/anko/files/3770171/ui.txt)

**Comment by Makentoshe** [comment]
I wouldn't bother much about the performance difference between xml and anko designed UI. The main feature of anko is a keeping you code easy by dividing  on a base components. It's will be much more prettier to see is to refactor your ui class. 

Is RelativeLayout in your ui is really needed? Can you replace/refactor them by ConstraintLayout? It will be much better too, i think.

About Anko performance i found this [publication on medium](https://medium.com/@c2q9450/performance-comparison-building-android-ui-with-code-anko-vs-xml-layout-cc0abb21c561). If you really bothers about performance you can think about trying to create your ui in another thread

**Comment by staney7** [comment]
@Makentoshe Thank your answer. Recently we want deploy a automatic transform component from XML to Anko layout and use it in our project. So we must sure about that the performance is better than xml layout.But sadly it doesn't satisfy us.

**Comment by Makentoshe** [comment]
@staney7 I have a little bit question about your "automatic transform component": Is it uses reflection API or something similar? I just don't understand how programming UI can be slower than xml parsing.

**Comment by staney7** [comment]
@Makentoshe We want use APT to transform xml to anko code in compile time like https://github.com/iReaderAndroid/X2C。I also don't understand why , but collected data show the performance is decreasing(sad)。

**Comment by Makentoshe** [comment]
@staney7 It's a really strange... May generated code be unoptimized?

**Comment by staney7** [comment]
@Makentoshe  The performance data above is using the ui.txt（I transform a layout in our project from  xml  to anko manually）. And now, the component development have not start because of the performance problem.

**Comment by Makentoshe** [comment]
Your UI seems legit, so I don't know why performance such bad. I saw the include function was used and its means the LayoutInflater will be called and some part of the UI will be created using XML parsing. Yes, the performance must be decreased but not be worse than full XML parsing. It blows my mind off.

**Comment by staney7** [comment]
Thank your answer ,If you have any idea about this, please contact to me.I will close the issue.
