### ISSUE TITLE
Missing View.dip() ?

### ISSUE THREAD

**Issue by lukaspili** [Kotlin/anko#95]
Hi,
Just wondering, is there any reason why the following dip() function extension is not present on View, but only on Context ?

```java
public inline fun View.dip(value: Int): Int = (value * (resources?.displayMetrics?.density ?: 0f)).toInt()
public inline fun View.dip(value: Float): Int = (value * (resources?.displayMetrics?.density ?: 0f)).toInt()
```

I find it useful to have this on View, when using Anko in custom view classes.
Thanks!

**Comment by Ribesg** [comment]
I'm not even sure why this function is associated to a class in fact. I'm a noob but I don't think the result depends on the View/Fragment/Activity/Context you use it on?

Shouldn't this function be "alone"?

**Comment by lukaspili** [comment]
It doesn't, but you still need to access the `Resources` instance in order to get the screen density.
Thus, having the `View.dip()` allows the following code:

```java
class PagerPageView(context: Context) : FrameLayout(context) {
       private fun setupView() {
            verticalLayout {
                lparams(matchParent, wrapContent) {
                    topMargin = dip(40) // with View.dip()
                    horizontalMargin = context.dip(20) // without View.dip()
                }
           }
       }
}
